export const es = {
  nav: { navigation:'Navegación principal',language:'Elegir idioma',skip:'Ir al contenido',home:'Inicio',features:'Funciones',allFeatures:'Ver todas las funciones',notes:'Guía de notas',rehearsal:'Ensayar',privacy:'Privacidad',terms:'Condiciones de uso',support:'Contacto',download:'Descargar en App Store',originalVersion:'Versión original' },
  home: { eyebrow:'Tingbo · Tus notas, en voz alta',title:'Escucha tu guion antes de presentarlo',description:'Tingbo lee las notas de cada diapositiva, avanza automáticamente y permite ver archivos PPT, PPTX y Keynote en el móvil.',intro:'Escucha las notas de cada diapositiva en orden. Al terminar, pasa a la siguiente; puedes seguir oyéndolas con la pantalla bloqueada. Corrige las frases que no suenen bien y vuelve a escucharlas.',formats:'iPhone y iPad · PPT, PPTX y Keynote · Sin cuenta',featureEyebrow:'Escucha, corrige y repite',featureTitle:'Ensaya tu presentación, diapositiva a diapositiva',featureIntro:'Oye tu guion en el orden real de la presentación y descubre qué conviene mejorar.',readerEyebrow:'Lectura ligera de diapositivas',readerTitle:'Mira la diapositiva mientras escuchas',readerText:'Desliza para cambiar de página, gira el teléfono y amplía los detalles. Las notas y los controles de audio siguen a mano.',screenshotAlt:'Pantalla de Tingbo con diapositiva, notas y controles de audio; interfaz en inglés',screenshotCaption:'Vista ilustrativa de la aplicación (interfaz en inglés).',stepsTitle:'Ensaya en tres pasos',faqTitle:'Preguntas frecuentes',ctaTitle:'Conoce tu guion antes de subir al escenario',ctaText:'Importa una presentación y empieza a escucharla.' },
  features: [['Lectura de notas por diapositiva','La voz del dispositivo lee las notas correspondientes a la diapositiva que ves.'],['Avance automático','Al terminar cada nota, continúa con la siguiente diapositiva. También puedes pausar, repetir o avanzar manualmente.'],['Audio en segundo plano','Sigue escuchando con la pantalla bloqueada o con auriculares; se pausa si estos se desconectan.'],['Edita mientras ensayas','Abre las notas, modifica una frase, guárdala y vuelve a escucharla.'],['Visor móvil de diapositivas','Desliza, cambia la orientación y amplía gráficos y detalles.'],['Historial y exportación','Reabre presentaciones importadas y exporta las notas en Markdown o una copia PPTX cuando esté disponible.']],
  featuresPage: {title:'Funciones de Tingbo',intro:'Diapositivas, notas y voz en una misma pantalla para ensayar sin perder el hilo.',formatsTitle:'Archivos y dispositivos',formatsText:'La versión 1.2 o posterior para iOS importa .ppt, .pptx y .key. Disponible para iPhone y iPad. Los diseños complejos pueden representarse de forma distinta según el archivo.'},
  notes: {title:'Cómo escuchar las notas de una presentación',intro:'Escribe tu guion en las notas de cada diapositiva; Tingbo lo leerá en orden.',tip:'Si una diapositiva no tiene notas, añade primero lo que quieras decir.',steps:[['Importa el archivo','Elige un PPT, PPTX o archivo Keynote (.key) en Archivos y comprueba las diapositivas y notas.'],['Pulsa reproducir','Escucha el texto de la diapositiva actual; al terminar puede avanzar automáticamente.'],['Corrige y repite','Edita las frases poco naturales, guarda los cambios y vuelve a reproducir esa página.']]},
  rehearsal: {title:'Ensaya escuchando tu presentación',intro:'Escuchar tu propio texto ayuda a detectar problemas de redacción, orden y transición.',tip:'Haz al menos una escucha completa antes de presentar y repite los pasajes que modifiques.',steps:[['Prepara el guion','Importa la presentación y completa las notas de cada diapositiva.'],['Escúchala de principio a fin','Comprueba que las palabras y las diapositivas avanzan juntas.'],['Mejora y vuelve a escuchar','Ajusta frases y omisiones hasta que el discurso suene natural.']]},
  faq: [['¿Cuál es la función principal de Tingbo?','Leer en voz alta las notas de cada diapositiva para que ensayes mientras ves la presentación.'],['¿Qué archivos admite?','En iOS 1.2 o posterior: PPT, PPTX y Keynote (.key).'],['¿Funciona en segundo plano?','Sí. Puede seguir sonando con la pantalla bloqueada y se pausa cuando se desconectan los auriculares.']],
  privacy: {title:'Política de privacidad de iOS',intro:'Cómo se tratan las presentaciones, las notas y las visitas a este sitio.',sections:[
    ['Resumen','Tingbo lee las notas de cada diapositiva. Las presentaciones y notas se guardan en tu dispositivo, salvo cuando utilizas el servicio de conversión descrito abajo. Las versiones de iOS con Firebase usan Firebase Analytics para conocer el uso de funciones; nuestros eventos personalizados no incluyen nombres de archivo ni texto de notas.'],
    ['Datos que no recopilamos','No hace falta crear una cuenta. Durante el uso normal no solicitamos nombre, correo, acceso a contactos ni fotos. No incluimos presentaciones, nombres de archivo ni texto de notas en eventos analíticos personalizados. La conversión en la nube puede enviar el archivo elegido; Firebase Analytics trata eventos de uso y datos técnicos relacionados.'],
    ['Tratamiento en el dispositivo','Las presentaciones importadas, las imágenes de diapositivas y las notas se guardan localmente. La lectura usa la función de texto a voz integrada en iOS.'],
    ['Conversión de presentaciones','Para mostrar PPT o PPTX como imágenes, algunas versiones pueden convertir el archivo. Puedes usar un servicio de tu red local; cuando se necesita conversión remota, la versión de iOS descrita aquí crea el trabajo mediante Cloudflare Worker y sube directamente el archivo elegido a CloudConvert. Solo se usa para la conversión solicitada, no para publicidad ni perfiles personales.'],
    ['Terceros','En la conversión remota, Cloudflare procesa la solicitud y CloudConvert recibe el archivo para generar el resultado. No vendemos ni alquilamos tus datos. GitHub Pages aloja el sitio y puede tratar registros de conexión, como la dirección IP, conforme a su política.'],
    ['Analítica de la app y el sitio','Las versiones de iOS con Firebase usan Firebase Analytics para registrar formato y origen de importación, resultado y duración del renderizado, cantidad de diapositivas, navegación e inicio de lectura. Los eventos personalizados no incluyen nombres de archivo, presentaciones ni texto de notas. Firebase también puede recopilar eventos automáticos e identificadores del dispositivo o de la instancia de la app. Por separado, Cloudflare Web Analytics mide visitas y rendimiento del sitio sin cookies analíticas ni seguimiento individual entre sitios; no accede al contenido de la app.'],
    ['Conservación y eliminación','Las presentaciones permanecen en el espacio local de la app. Puedes borrar cada una en el historial; al desinstalar la app se elimina su contenido almacenado en el dispositivo.'],
    ['Menores','La app no está dirigida a menores de 13 años y no recopilamos deliberadamente sus datos personales.'],
    ['Cambios','Podemos actualizar esta política e indicar una nueva fecha. Si sigues usando la app tras la entrada en vigor, aceptas la versión actualizada.'],
    ['Contacto','Para consultas sobre privacidad o tratamiento de datos: m15568817011@163.com.']
  ]},
  terms: {title:'Condiciones de uso de iOS',intro:'Lee estas condiciones antes de utilizar Tingbo para iOS.',sections:[
    ['Aceptación','Al descargar, instalar o usar Tingbo aceptas estas condiciones. Si no estás de acuerdo, no uses la app.'],
    ['Licencia','Con sujeción a estas condiciones y a las de Apple App Store, recibes una licencia limitada, no exclusiva, intransferible y revocable para uso personal y no comercial en tus dispositivos Apple.'],
    ['Tu contenido','Conservas los derechos sobre las presentaciones y notas importadas. Eres responsable de tener permiso para usarlas y tratarlas.'],
    ['Funcionamiento','La app muestra las diapositivas como imágenes y lee las notas mediante la voz del dispositivo. La conversión puede hacerse en tu red local o, si configuras un servicio remoto, el archivo elegido puede ser tratado por terceros solo para la conversión solicitada. Consulta la política de privacidad.'],
    ['Uso permitido','No practiques ingeniería inversa, descompilación ni desmontaje; no uses la app ilegalmente ni la copies, vendas, alquiles, sublicencies o distribuyas; no importes contenido sin autorización.'],
    ['Servicios de terceros','Los proveedores de conversión remota pueden procesar archivos para generar imágenes de diapositivas. El alojamiento web y otros servicios tienen sus propias condiciones y políticas.'],
    ['Propiedad intelectual','El diseño, código, imágenes y demás elementos de la app nos pertenecen a nosotros o a nuestros licenciantes y están protegidos por ley. No se conceden derechos adicionales.'],
    ['Exención de garantías','La app se ofrece «tal cual» y «según disponibilidad», sin garantías expresas ni implícitas de comerciabilidad, idoneidad o no infracción. No garantizamos disponibilidad ininterrumpida, ausencia de errores ni seguridad absoluta.'],
    ['Limitación de responsabilidad','En la medida máxima permitida por ley, no respondemos por daños indirectos, incidentales, especiales, consecuentes o punitivos, ni por pérdida de beneficios o datos derivada del uso, aunque se nos haya advertido.'],
    ['Terminación','Puedes dejar de usar la app en cualquier momento. Podemos suspender o finalizar la licencia si incumples estas condiciones; entonces debes dejar de usarla y eliminarla del dispositivo.'],
    ['Cambios','Podemos publicar condiciones actualizadas con una nueva fecha. Seguir usando la app una vez vigentes implica aceptarlas.'],
    ['Ley aplicable','Se aplica la legislación de tu país o región de residencia, sin limitar tus derechos imperativos como consumidor.'],
    ['Contacto','Escríbenos a m15568817011@163.com si tienes preguntas.']
  ]},
  androidPrivacy: {title:'Política de privacidad de Android',intro:'Tratamiento de archivos, voz y datos en Tingbo para Android; destinado a mayores de 13 años.',sections:[
    ['Archivos y datos locales','Tras importar con el selector de Android, la app guarda una copia local, diapositivas, nombre y fecha de importación, notas editadas, historial, preferencias y cachés de voz y exportación. Los archivos exportados se guardan donde elijas, incluso en un proveedor de nube.'],
    ['Conversión en línea','Si hace falta convertir o representar en línea, se sube la presentación completa, que puede contener texto, imágenes, notas y objetos. El original pasa por Cloudflare Worker a CloudConvert y el resultado vuelve por el Worker. CloudConvert afirma borrar trabajos y datos automáticamente 24 horas después de completarlos; según su política, registros como IP, User-Agent, hora y estadísticas pueden conservarse 180 días. Cloudflare también puede tratar datos de red y solicitud; los proveedores pueden operar en otros países.'],
    ['Texto a voz de Android','Las notas se entregan al motor de voz habilitado en el dispositivo. Al abrir, cambiar de página o editar, puede prepararse el texto de páginas actuales y cercanas antes de pulsar reproducir. Que funcione sin conexión depende del motor, voz y ajustes; una voz en línea puede enviar texto y datos de solicitud a su proveedor. Puedes cambiar el motor en los ajustes del sistema.'],
    ['Copias y transferencia','Si están activadas, Android o el fabricante pueden copiar, transferir o restaurar datos aptos de la app, incluso presentaciones y preferencias, según versión, cuenta y ajustes. Es independiente del servicio de conversión de Tingbo.'],
    ['Conservación y borrado','Borrar una presentación del historial elimina su copia local, notas modificadas y registro, pero quizá no todos los cachés de voz o exportación. Gestiona por separado las exportaciones, originales en otros proveedores y copias del sistema. El borrado en la app no solicita eliminación inmediata al proveedor de conversión; rigen sus plazos. Para ayuda, escribe sin adjuntar primero la presentación completa.'],
    ['Soporte','Si escribes al soporte o envías una solicitud de privacidad, recibimos tu dirección, mensaje y archivos que adjuntes voluntariamente, y los usamos para responder. Evita compartir datos innecesarios.'],
    ['Menores','La app está destinada a personas de 13 años o más, no a menores de 13. Si un menor envió datos, contáctanos; se respetan las normas locales de participación parental.'],
    ['Seguridad y cambios','La conversión usa HTTPS, que no equivale a cifrado de extremo a extremo ni impide que el proveedor lea el archivo. El motor de voz y las copias tienen ajustes propios. Actualizaremos esta política si cambia el tratamiento y avisaremos o pediremos consentimiento cuando proceda.'],
    ['Este sitio','GitHub Pages aloja estas páginas y puede mantener registros estándar. Cloudflare Web Analytics mide visitas, procedencia y rendimiento sin cookies analíticas ni seguimiento entre sitios; no analiza presentaciones ni la reproducción de la app.']
  ]},
  harmonyPrivacy: {title:'Política de privacidad de HarmonyOS',intro:'Cómo Tingbo para HarmonyOS trata archivos PPTX y notas en tu dispositivo.',sections:[
    ['Resumen','La app importa PPTX, muestra diapositivas y lee notas. No requiere cuenta; el archivo, las diapositivas y las notas se procesan solo en el dispositivo, sin subirlos a servidores nuestros ni de terceros.'],
    ['Datos recopilados','La app no recopila, almacena ni sube nombre, teléfono, correo, identificadores, ubicación, contactos, identificadores publicitarios, actividad ni contenido de presentaciones; no integra anuncios, analítica ni rastreadores.'],
    ['Archivos locales','Solo lee el PPTX que eliges en el selector del sistema. Descomprimir, interpretar imágenes y notas se hace localmente. Archivos, resultados y notas modificadas permanecen en el espacio local de la app.'],
    ['Voz sin conexión','La lectura usa la síntesis sin conexión de HarmonyOS Core Speech Kit. Ni las notas ni el audio generado se envían a nuestros servidores o a terceros.'],
    ['Red y terceros','La app no solicita permiso de Internet y no ofrece conexión, conversión en la nube, voz en línea ni servicios externos que suban tu contenido.'],
    ['Conservación y borrado','Puedes borrar presentaciones del historial. Desinstalar la app elimina los datos que almacena en el dispositivo.'],
    ['Menores','La app no está dirigida específicamente a menores de 14 años y no recopila deliberadamente sus datos personales.'],
    ['Cambios','Si cambia esta política, actualizaremos la página y la fecha de revisión.'],
    ['Contacto','Escribe a m15568817011@163.com si tienes preguntas.'],
    ['Analítica de la web','GitHub Pages puede conservar registros estándar. Cloudflare Web Analytics mide visitas y rendimiento sin cookies analíticas ni rastreo entre sitios. Solo afecta a la web: no da acceso a Internet a la app HarmonyOS ni envía archivos, notas o audio.']
  ]}
};

export const fr = {
  nav:{navigation:'Navigation principale',language:'Choisir la langue',skip:'Aller au contenu',home:'Accueil',features:'Fonctionnalités',allFeatures:'Toutes les fonctionnalités',notes:'Guide des notes',rehearsal:'Répéter',privacy:'Confidentialité',terms:"Conditions d’utilisation",support:'Contact',download:"Télécharger sur l’App Store",originalVersion:'Version originale'},
  home:{eyebrow:'Tingbo · Écoutez vos notes de présentation',title:'Écoutez votre texte, présentez avec assurance',description:'Tingbo lit les notes de chaque diapositive, passe automatiquement à la suivante et affiche les fichiers PPT, PPTX et Keynote sur mobile.',intro:'Écoutez vos notes diapositive par diapositive. La lecture peut avancer seule et continuer écran verrouillé. Modifiez une phrase maladroite, puis réécoutez-la.',formats:'iPhone et iPad · PPT, PPTX, Keynote · Sans compte',featureEyebrow:'Écouter, corriger, recommencer',featureTitle:'Répétez votre présentation à votre rythme',featureIntro:'Suivez vos diapositives dans l’ordre et repérez les passages à améliorer.',readerEyebrow:'Lecture mobile légère',readerTitle:'Regardez la diapositive tout en écoutant',readerText:'Balayez pour changer de page, passez en mode paysage et zoomez sur les détails. Les notes et commandes audio restent accessibles.',screenshotAlt:'Écran Tingbo montrant une diapositive, des notes et les commandes audio en anglais',screenshotCaption:"Aperçu de l’application (interface en anglais).",stepsTitle:'Répétez en trois étapes',faqTitle:'Questions fréquentes',ctaTitle:'Maîtrisez votre texte avant de prendre la parole',ctaText:'Importez votre présentation et lancez la lecture.'},
  features:[['Lecture des notes diapositive par diapositive','La synthèse vocale de votre appareil lit les notes associées à la diapositive affichée.'],['Passage automatique','Une fois les notes lues, la diapositive suivante s’affiche. Vous pouvez interrompre, rejouer ou naviguer manuellement.'],['Écoute en arrière-plan','Continuez écran verrouillé ou avec un casque ; la lecture s’interrompt si le casque est déconnecté.'],['Corriger pendant la répétition','Ouvrez les notes, modifiez une phrase, enregistrez et réécoutez.'],['Visionneuse de diapositives','Balayez, tournez l’écran et zoomez sur les graphiques et petits détails.'],['Historique et export','Rouvrez une présentation importée ; exportez les notes en Markdown ou une copie PPTX lorsque disponible.']],
  featuresPage:{title:'Fonctionnalités de Tingbo',intro:'Diapositives, notes et audio dans le même écran pour répéter sans perdre le fil.',formatsTitle:'Fichiers et appareils',formatsText:'Sur iOS 1.2 ou ultérieur, importez les fichiers .ppt, .pptx et .key. Disponible sur iPhone et iPad. Le rendu de mises en page complexes peut varier selon le fichier.'},
  notes:{title:'Faire lire les notes de présentation',intro:'Inscrivez votre texte dans les notes de chaque diapositive ; Tingbo le lira dans l’ordre.',tip:'Si une diapositive ne contient pas de notes, ajoutez d’abord ce que vous souhaitez dire.',steps:[['Importer','Sélectionnez un PPT, PPTX ou fichier Keynote (.key) dans Fichiers et vérifiez diapositives et notes.'],['Lancer la lecture','Écoutez les notes de la diapositive affichée ; la suivante peut s’ouvrir automatiquement.'],['Corriger et réécouter','Modifiez une tournure peu naturelle, enregistrez et rejouez cette diapositive.']]},
  rehearsal:{title:'Répéter en écoutant sa présentation',intro:'Écouter votre texte permet de repérer les phrases, l’ordre ou les transitions à retravailler.',tip:'Écoutez la présentation entière au moins une fois avant le jour J, puis répétez les passages corrigés.',steps:[['Préparer les notes','Importez la présentation et complétez les notes de chaque diapositive.'],['Écouter du début à la fin','Vérifiez que le texte correspond à chaque diapositive.'],['Améliorer et rejouer','Corrigez les phrases et oublis jusqu’à ce que le discours sonne juste.']]},
  faq:[['À quoi sert principalement Tingbo ?','À lire les notes de chaque diapositive pour répéter tout en regardant la présentation.'],['Quels fichiers sont acceptés ?','PPT, PPTX et Keynote (.key) sur iOS 1.2 ou ultérieur.'],['Peut-on écouter en arrière-plan ?','Oui, y compris écran verrouillé ; la lecture se met en pause si le casque est déconnecté.']],
  privacy:{title:'Politique de confidentialité iOS',intro:'Comment les présentations, les notes et les visites du site sont traitées.',sections:[
    ['Présentation','Tingbo lit les notes diapositive par diapositive. Présentations et notes sont stockées sur votre appareil, sauf si vous utilisez le service de conversion décrit ci-dessous. Les versions iOS intégrant Firebase utilisent Firebase Analytics pour mesurer l’usage des fonctions ; nos événements personnalisés ne contiennent ni noms de fichiers ni texte des notes.'],
    ['Données non collectées','Aucun compte n’est nécessaire. En utilisation normale, nous ne demandons ni nom, ni adresse électronique, ni accès aux contacts ou aux photos. Nos événements d’analyse personnalisés ne contiennent ni présentations, ni noms de fichiers, ni texte des notes. Une conversion distante peut envoyer le fichier choisi ; Firebase Analytics traite les événements d’utilisation et des données techniques associées.'],
    ['Traitement local','Les présentations importées, images de diapositives et notes restent dans l’espace local de l’application. La lecture utilise la synthèse vocale intégrée à iOS.'],
    ['Conversion','Pour afficher un PPT ou PPTX en images, certaines versions peuvent convertir le fichier. Un service sur votre réseau local peut être utilisé ; en cas de conversion distante, la version iOS décrite ici crée la tâche via Cloudflare Worker et envoie directement le fichier choisi à CloudConvert. Le fichier sert uniquement à la conversion demandée, pas à la publicité ni au profilage.'],
    ['Services tiers','Lors d’une conversion distante, Cloudflare traite la demande et CloudConvert reçoit le fichier pour produire le résultat. Nous ne vendons ni ne louons vos données. Le site est hébergé par GitHub Pages, qui peut traiter des journaux de connexion comme l’adresse IP selon sa politique.'],
    ['Analyse de l’application et du site','Les versions iOS intégrant Firebase utilisent Firebase Analytics pour enregistrer format et origine des imports, résultat et durée du rendu, nombre de diapositives, navigation et début de lecture. Nos événements personnalisés ne contiennent ni noms de fichiers, ni présentations, ni texte des notes. Firebase peut aussi collecter des événements automatiques et des identifiants de l’appareil ou de l’instance de l’application. Séparément, Cloudflare Web Analytics mesure visites et performances du site sans cookies analytiques ni suivi individuel entre sites ; il n’accède pas au contenu de l’application.'],
    ['Conservation et suppression','Les présentations restent dans l’espace local de l’application. Vous pouvez les supprimer de l’historique ; la désinstallation supprime les données conservées sur l’appareil.'],
    ['Enfants','L’application ne s’adresse pas aux moins de 13 ans et nous ne collectons pas sciemment leurs données personnelles.'],
    ['Modifications','Nous pouvons modifier cette politique et afficher une nouvelle date. Continuer à utiliser l’application après l’entrée en vigueur vaut acceptation.'],
    ['Contact','Pour toute question sur la confidentialité : m15568817011@163.com.']
  ]},
  terms:{title:'Conditions d’utilisation iOS',intro:'Veuillez lire ces conditions avant d’utiliser Tingbo sur iOS.',sections:[
    ['Acceptation','Télécharger, installer ou utiliser Tingbo signifie accepter ces conditions. Sinon, n’utilisez pas l’application.'],
    ['Licence','Sous réserve de ces conditions et de celles de l’Apple App Store, nous accordons une licence limitée, non exclusive, non transférable et révocable pour un usage personnel non commercial sur vos appareils Apple.'],
    ['Votre contenu','Vous conservez vos droits sur les présentations et notes importées. Il vous appartient de disposer des autorisations nécessaires pour les utiliser et les traiter.'],
    ['Fonctionnement','Les diapositives sont affichées en images et les notes lues par la synthèse vocale de l’appareil. La conversion peut se faire sur votre réseau local ou, si vous configurez un service distant, le fichier choisi peut être traité par un tiers uniquement pour la conversion demandée. Voir la politique de confidentialité.'],
    ['Usage autorisé','Ne procédez pas à l’ingénierie inverse, la décompilation ou le démontage ; n’utilisez pas l’application illégalement, ne la copiez, vendez, louez, sous-licenciez ou distribuez pas et n’importez pas de contenu sans droit.'],
    ['Services tiers','Des prestataires peuvent traiter les fichiers pour générer des images lors d’une conversion distante. L’hébergement du site et d’autres services sont soumis à leurs propres conditions et politiques.'],
    ['Propriété intellectuelle','Le design, le code, les images et autres éléments de l’application nous appartiennent ou appartiennent à nos concédants et sont protégés par la loi. Aucun autre droit n’est concédé.'],
    ['Absence de garantie','L’application est fournie « en l’état » et « selon disponibilité », sans garantie explicite ou implicite, notamment de qualité marchande, d’adéquation à un usage ou de non-contrefaçon. Nous ne garantissons ni continuité, ni absence d’erreurs, ni sécurité absolue.'],
    ['Limitation de responsabilité','Dans les limites de la loi applicable, nous ne répondons pas des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, ni des pertes de bénéfices ou de données liés à l’utilisation, même prévenus de leur possibilité.'],
    ['Résiliation','Vous pouvez cesser d’utiliser l’application à tout moment. Nous pouvons suspendre ou résilier la licence en cas de violation ; vous devez alors cesser de l’utiliser et la supprimer de l’appareil.'],
    ['Modifications','Nous pouvons publier des conditions actualisées et leur date. Continuer à utiliser l’application après leur entrée en vigueur vaut acceptation.'],
    ['Droit applicable','Le droit de votre pays ou région de résidence s’applique, sans limiter vos droits impératifs de consommateur.'],
    ['Contact','Écrivez à m15568817011@163.com pour toute question.']
  ]},
  androidPrivacy:{title:'Politique de confidentialité Android',intro:'Traitement des fichiers, de la voix et des données sur Tingbo Android, destiné aux personnes d’au moins 13 ans.',sections:[
    ['Fichiers et données locales','Après importation via le sélecteur Android, l’application conserve localement une copie, les diapositives, le nom et la date d’importation, les notes modifiées, l’historique, les préférences et des caches audio et d’export. Les exportations vont vers l’emplacement choisi, éventuellement un service cloud.'],
    ['Conversion en ligne','Si un rendu distant est requis, tout le fichier sélectionné est envoyé, y compris éventuellement texte, images, notes et objets intégrés. L’original passe par Cloudflare Worker vers CloudConvert, et le résultat revient via Worker. CloudConvert indique supprimer automatiquement les tâches et données 24 heures après leur fin ; sa politique mentionne des journaux IP, User-Agent, horodatage et statistiques pouvant être gardés 180 jours. Cloudflare peut aussi traiter des données réseau et de requête ; le traitement peut avoir lieu à l’étranger.'],
    ['Synthèse vocale Android','Les notes sont transmises au moteur vocal activé sur l’appareil. À l’ouverture, au changement de page ou après modification, le texte de la page et des pages voisines peut être préparé avant même la lecture. Le fonctionnement hors ligne dépend du moteur, de la voix et des réglages ; une voix en ligne peut envoyer texte et données de requête à son fournisseur. Vous pouvez changer de moteur dans les réglages système.'],
    ['Sauvegarde et transfert','Si activés, Android ou le fabricant peuvent sauvegarder, transférer ou restaurer des données éligibles de l’application, y compris présentations et préférences, selon la version, le compte et les réglages. C’est distinct du service de conversion.'],
    ['Conservation et suppression','Supprimer une présentation de l’historique efface sa copie locale, les notes modifiées et l’entrée, mais pas forcément tous les caches audio ou d’export. Gérez séparément exportations, originaux ailleurs et sauvegardes système. La suppression dans l’application ne demande pas l’effacement immédiat au prestataire de conversion ; ses délais s’appliquent. Pour obtenir de l’aide, écrivez-nous sans joindre d’emblée le fichier complet.'],
    ['Assistance','Si vous contactez l’assistance ou faites une demande de confidentialité, nous recevons votre adresse, message et pièces jointes volontaires pour y répondre. Évitez les données inutiles.'],
    ['Enfants','L’application s’adresse aux 13 ans et plus, pas aux moins de 13 ans. Contactez-nous si un enfant a envoyé des données ; les règles locales de participation parentale restent applicables.'],
    ['Sécurité et modifications','La conversion utilise HTTPS, qui n’est pas un chiffrement de bout en bout et n’empêche pas le prestataire de lire le fichier. Le moteur vocal et les sauvegardes ont leurs propres réglages. Nous actualiserons cette politique en cas de changement et fournirons les avis ou consentements requis.'],
    ['Ce site','GitHub Pages héberge ces pages et peut conserver des journaux standards. Cloudflare Web Analytics mesure visites, provenance et performances sans cookies analytiques ni suivi entre sites ; cela ne concerne ni les présentations ni la lecture dans l’application.']
  ]},
  harmonyPrivacy:{title:'Politique de confidentialité HarmonyOS',intro:'Traitement local des fichiers PPTX et des notes dans Tingbo pour HarmonyOS.',sections:[
    ['Présentation','L’application importe des PPTX, affiche les diapositives et lit les notes. Aucun compte n’est nécessaire : fichiers, diapositives et notes sont traités uniquement sur l’appareil, sans envoi à nos serveurs ou à des tiers.'],
    ['Données collectées','L’application ne collecte, conserve ni transmet nom, téléphone, courriel, identifiants, localisation, contacts, identifiants publicitaires, activité ou contenu des présentations ; elle n’intègre ni publicité, ni analyse, ni suivi.'],
    ['Fichiers locaux','Seul le PPTX choisi dans le sélecteur système est lu. Décompression et analyse des images et notes se font localement. Les fichiers, résultats et notes modifiées restent dans l’espace local de l’application.'],
    ['Voix hors ligne','La lecture utilise la synthèse vocale hors ligne de HarmonyOS Core Speech Kit. Ni le texte des notes ni l’audio généré ne sont envoyés à nos serveurs ou à des tiers.'],
    ['Réseau et tiers','L’application ne demande pas d’autorisation Internet et ne propose ni connexion, ni conversion cloud, ni voix en ligne, ni autre service envoyant votre contenu.'],
    ['Conservation et suppression','Vous pouvez supprimer les présentations de l’historique. La désinstallation efface les données conservées par l’application sur l’appareil.'],
    ['Enfants','L’application ne vise pas spécifiquement les moins de 14 ans et ne collecte pas sciemment leurs données personnelles.'],
    ['Modifications','Si cette politique change, nous actualiserons la page et la date de révision.'],
    ['Contact','Pour toute question : m15568817011@163.com.'],
    ['Analyse du site','GitHub Pages peut conserver des journaux standards. Cloudflare Web Analytics mesure visites et performances sans cookies analytiques ni suivi entre sites. Cela concerne seulement le site : l’application HarmonyOS ne reçoit aucun accès Internet et n’envoie ni fichier, ni note, ni audio.']
  ]}
};

export const de = {
  nav:{navigation:'Hauptnavigation',language:'Sprache wählen',skip:'Zum Inhalt springen',home:'Startseite',features:'Funktionen',allFeatures:'Alle Funktionen',notes:'Anleitung für Notizen',rehearsal:'Präsentation üben',privacy:'Datenschutz',terms:'Nutzungsbedingungen',support:'Kontakt',download:'Im App Store laden',originalVersion:'Originalfassung'},
  home:{eyebrow:'Tingbo · Vortragsnotizen anhören',title:'Hör dir dein Skript an. Präsentiere sicherer.',description:'Tingbo liest Notizen Folie für Folie vor, wechselt automatisch weiter und zeigt PPT-, PPTX- und Keynote-Dateien auf dem Smartphone.',intro:'Höre dir die Notizen zu jeder Folie der Reihe nach an. Nach dem Vorlesen geht es automatisch weiter; auch bei gesperrtem Bildschirm kannst du zuhören. Überarbeite holprige Sätze und höre sie erneut.',formats:'iPhone und iPad · PPT, PPTX, Keynote · Kein Konto nötig',featureEyebrow:'Anhören, verbessern, wiederholen',featureTitle:'Übe deinen Vortrag Folie für Folie',featureIntro:'Höre dein Skript in der richtigen Reihenfolge und erkenne, was noch besser werden kann.',readerEyebrow:'Leichter mobiler Folienleser',readerTitle:'Folien ansehen und Skript anhören',readerText:'Wische durch Folien, drehe das Gerät und vergrößere Details. Notizen und Audiosteuerung bleiben griffbereit.',screenshotAlt:'Tingbo-Ansicht mit Folie, Notizen und Audiosteuerung in englischer Oberfläche',screenshotCaption:'Beispielansicht der App (englische Oberfläche).',stepsTitle:'In drei Schritten zur Probe',faqTitle:'Häufige Fragen',ctaTitle:'Kenne dein Skript, bevor du auftrittst',ctaText:'Präsentation importieren und von der ersten Folie an zuhören.'},
  features:[['Notizen pro Folie vorlesen','Die Sprachsynthese des Geräts liest die Notizen zur aktuell angezeigten Folie vor.'],['Automatisch weiterblättern','Nach dem Vorlesen erscheint die nächste Folie. Du kannst jederzeit pausieren, wiederholen oder manuell wechseln.'],['Wiedergabe im Hintergrund','Höre bei gesperrtem Bildschirm oder mit Kopfhörern weiter; beim Trennen der Kopfhörer pausiert die Wiedergabe.'],['Skript beim Üben bearbeiten','Öffne die Notizen, verbessere einen Satz, speichere und höre ihn erneut.'],['Folien bequem lesen','Wischen, Bildschirm drehen und mit zwei Fingern Details und Diagramme vergrößern.'],['Verlauf und Export','Öffne importierte Präsentationen erneut und exportiere Notizen als Markdown oder, falls verfügbar, eine PPTX-Kopie.']],
  featuresPage:{title:'Funktionen von Tingbo',intro:'Folien, Notizen und Sprachwiedergabe an einem Ort – für Proben ohne Unterbrechung.',formatsTitle:'Dateien und Geräte',formatsText:'iOS ab Version 1.2 importiert .ppt, .pptx und .key. Verfügbar für iPhone und iPad. Komplexe Layouts können je nach Datei abweichend dargestellt werden.'},
  notes:{title:'Präsentationsnotizen vorlesen lassen',intro:'Schreibe deinen Vortrag in die Notizen jeder Folie; Tingbo liest ihn der Reihe nach vor.',tip:'Füge Folien ohne Notizen zuerst deinen gewünschten Text hinzu.',steps:[['Datei importieren','Wähle PPT, PPTX oder Keynote (.key) in „Dateien“ und prüfe Folien und Notizen.'],['Wiedergabe starten','Höre die Notizen der aktuellen Folie; danach kann automatisch weitergeschaltet werden.'],['Verbessern und erneut hören','Bearbeite unnatürliche Formulierungen, speichere und spiele die Folie erneut ab.']]},
  rehearsal:{title:'Präsentation durch Zuhören üben',intro:'Beim Anhören fallen holprige Sätze, Reihenfolge und Übergänge leichter auf.',tip:'Höre die gesamte Präsentation vor dem Vortrag mindestens einmal an und wiederhole überarbeitete Stellen.',steps:[['Skript vorbereiten','Importiere die Präsentation und ergänze die Notizen jeder Folie.'],['Alles der Reihe nach hören','Prüfe, ob Folien und gesprochener Text zusammenpassen.'],['Überarbeiten und wiederholen','Verbessere Sätze und fehlende Punkte, bis dein Vortrag natürlich klingt.']]},
  faq:[['Was ist die Hauptfunktion von Tingbo?','Die App liest die Notizen jeder Folie vor, damit du beim Anschauen der Präsentation üben kannst.'],['Welche Dateien werden unterstützt?','PPT, PPTX und Keynote (.key) ab iOS 1.2.'],['Kann ich im Hintergrund zuhören?','Ja, auch bei gesperrtem Bildschirm. Beim Trennen der Kopfhörer pausiert die Wiedergabe.']],
  privacy:{title:'Datenschutzerklärung für iOS',intro:'So werden Präsentationen, Notizen und Besuche dieser Website verarbeitet.',sections:[
    ['Überblick','Tingbo liest Foliennotizen vor. Präsentationen und Notizen werden auf deinem Gerät gespeichert, außer wenn du den unten beschriebenen Konvertierungsdienst nutzt. iOS-Versionen mit Firebase verwenden Firebase Analytics für die Funktionsnutzung; unsere benutzerdefinierten Ereignisse enthalten weder Dateinamen noch Notiztexte.'],
    ['Nicht erhobene Daten','Es ist kein Konto nötig. Bei normaler Nutzung fragen wir weder nach Namen noch nach E-Mail-Adresse oder Zugriff auf Kontakte oder Fotos. Benutzerdefinierte Analyseereignisse enthalten keine Präsentationen, Dateinamen oder Notiztexte. Bei Cloud-Konvertierung kann die ausgewählte Datei übertragen werden; Firebase Analytics verarbeitet Nutzungsereignisse und zugehörige technische Daten.'],
    ['Verarbeitung auf dem Gerät','Importierte Präsentationen, Folienbilder und Notizen bleiben im lokalen App-Speicher. Das Vorlesen nutzt die integrierte iOS-Sprachausgabe.'],
    ['Umwandlung von Präsentationen','Zur Anzeige von PPT/PPTX als Folienbilder können einige Versionen die Datei umwandeln. Ein Dienst im eigenen lokalen Netzwerk ist möglich; bei nötiger Fernumwandlung erstellt die hier beschriebene iOS-Version einen Auftrag über Cloudflare Worker und lädt die gewählte Datei direkt zu CloudConvert. Die Datei dient nur der gewünschten Umwandlung, nicht Werbung oder Profilbildung.'],
    ['Drittanbieter','Bei Fernumwandlung verarbeitet Cloudflare die Anfrage; CloudConvert empfängt die Datei und erzeugt das Ergebnis. Wir verkaufen oder vermieten keine Daten. GitHub Pages hostet die Website und kann nach eigener Richtlinie übliche Verbindungsprotokolle wie IP-Adressen verarbeiten.'],
    ['App- und Website-Analyse','iOS-Versionen mit Firebase verwenden Firebase Analytics für Importformat und -quelle, Rendering-Ergebnis und -dauer, Folienzahl, Navigation und Vorlesestart. Benutzerdefinierte Ereignisse enthalten keine Dateinamen, Präsentationen oder Notiztexte. Firebase kann außerdem automatische Ereignisse und Geräte- oder App-Instanzkennungen erfassen. Unabhängig davon misst Cloudflare Web Analytics Besuche und Leistung der Website ohne Analyse-Cookies oder websiteübergreifendes Tracking einzelner Personen; es kann nicht auf App-Inhalte zugreifen.'],
    ['Aufbewahrung und Löschung','Präsentationen bleiben lokal in der App. Einzelne Dateien kannst du im Verlauf löschen; durch Deinstallation werden die auf dem Gerät gespeicherten App-Daten entfernt.'],
    ['Kinder','Die App richtet sich nicht an Kinder unter 13 Jahren; wir erfassen wissentlich keine personenbezogenen Daten von ihnen.'],
    ['Änderungen','Wir können diese Erklärung mit neuem Datum aktualisieren. Wer die App nach Inkrafttreten weiter nutzt, akzeptiert die neue Fassung.'],
    ['Kontakt','Fragen zum Datenschutz: m15568817011@163.com.']
  ]},
  terms:{title:'Nutzungsbedingungen für iOS',intro:'Bitte lies diese Bedingungen vor der Nutzung von Tingbo für iOS.',sections:[
    ['Zustimmung','Mit Download, Installation oder Nutzung von Tingbo akzeptierst du diese Bedingungen. Falls nicht, nutze die App nicht.'],
    ['Lizenz','Vorbehaltlich dieser Bedingungen und der Apple-App-Store-Bedingungen erhältst du eine beschränkte, nicht exklusive, nicht übertragbare und widerrufliche Lizenz zur privaten, nicht kommerziellen Nutzung auf deinen Apple-Geräten.'],
    ['Deine Inhalte','Die Rechte an importierten Präsentationen und Notizen bleiben bei dir. Du musst sicherstellen, dass du sie verwenden und verarbeiten darfst.'],
    ['Funktionsweise','Die App zeigt Folien als Bilder und liest Notizen mit der Geräte-Sprachausgabe. Umwandlung kann im eigenen Netzwerk erfolgen; wenn du einen Ferndienst einrichtest, kann die ausgewählte Datei nur für die gewünschte Umwandlung an Dritte gehen. Siehe Datenschutzerklärung.'],
    ['Zulässige Nutzung','Reverse Engineering, Dekompilieren und Zerlegen sind untersagt; nutze die App nicht rechtswidrig, kopiere, verkaufe, vermiete, unterlizenziere oder verbreite sie nicht und importiere keine Inhalte ohne Berechtigung.'],
    ['Drittanbieter','Fernumwandlungsdienste können Dateien zur Erstellung von Folienbildern verarbeiten. Website-Hosting und weitere Dienste haben eigene Bedingungen und Richtlinien.'],
    ['Geistiges Eigentum','Design, Code, Bilder und weitere App-Inhalte gehören uns oder unseren Lizenzgebern und sind gesetzlich geschützt. Weitere Rechte werden nicht eingeräumt.'],
    ['Gewährleistungsausschluss','Die App wird „wie besehen“ und „wie verfügbar“ ohne ausdrückliche oder stillschweigende Garantien bereitgestellt, etwa für Marktgängigkeit, Eignung oder Nichtverletzung. Unterbrechungsfreiheit, Fehlerfreiheit und absolute Sicherheit werden nicht zugesichert.'],
    ['Haftungsbeschränkung','Soweit gesetzlich zulässig, haften wir nicht für mittelbare, beiläufige, besondere, Folge- oder Strafschäden sowie entgangene Gewinne oder Datenverluste aus der Nutzung, auch wenn wir auf die Möglichkeit hingewiesen wurden.'],
    ['Beendigung','Du kannst die Nutzung jederzeit einstellen. Bei Verstößen können wir die Lizenz aussetzen oder beenden; dann musst du die App nicht mehr nutzen und vom Gerät entfernen.'],
    ['Änderungen','Wir können neue Bedingungen und ein Aktualisierungsdatum veröffentlichen. Weitere Nutzung nach Inkrafttreten bedeutet Zustimmung.'],
    ['Anwendbares Recht','Es gilt das Recht deines Wohnsitzlandes oder deiner Region, ohne zwingende Verbraucherrechte einzuschränken.'],
    ['Kontakt','Fragen an m15568817011@163.com.']
  ]},
  androidPrivacy:{title:'Datenschutzerklärung für Android',intro:'Verarbeitung von Dateien, Sprache und Daten in Tingbo für Android; für Personen ab 13 Jahren.',sections:[
    ['Lokale Dateien und Daten','Nach Import über die Android-Dateiauswahl speichert die App lokal eine Arbeitskopie, Folien, Dateinamen und Importzeit, bearbeitete Notizen, Verlauf, Einstellungen sowie Sprach- und Export-Caches. Exporte gehen an den gewählten Ort, möglicherweise einen Cloud-Dienst.'],
    ['Online-Umwandlung','Ist Online-Konvertierung oder Darstellung nötig, wird die gesamte gewählte Präsentation hochgeladen, möglicherweise einschließlich Text, Bildern, Notizen und eingebetteten Inhalten. Das Original gelangt über Cloudflare Worker zu CloudConvert, das Ergebnis über Worker zurück. CloudConvert gibt an, Aufträge und Daten 24 Stunden nach Abschluss automatisch zu löschen; laut dessen Richtlinie können IP-, User-Agent-, Zeit- und Statistikprotokolle 180 Tage aufbewahrt werden. Cloudflare kann Netzwerk- und Anfragedaten verarbeiten; die Anbieter können im Ausland tätig sein.'],
    ['Android-Sprachausgabe','Notizen werden an die aktivierte Android-Sprachausgabe übergeben. Beim Öffnen, Folienwechsel oder Bearbeiten kann Text der aktuellen und benachbarten Folien schon vor dem Drücken von „Abspielen“ vorbereitet werden. Ob dies offline bleibt, hängt von Engine, Stimme und Einstellungen ab; Online-Stimmen können Text und Anfragedaten an den Anbieter senden. Die Engine lässt sich in den Systemeinstellungen ändern.'],
    ['Sicherung und Übertragung','Falls aktiviert, können Android oder der Gerätehersteller geeignete App-Daten einschließlich Präsentationen und Einstellungen je nach Version, Konto und Konfiguration sichern, übertragen oder wiederherstellen. Das ist vom Umwandlungsdienst getrennt.'],
    ['Aufbewahrung und Löschung','Das Löschen im Verlauf entfernt lokale Kopie, bearbeitete Notizen und Eintrag, aber möglicherweise nicht jeden Sprach- oder Export-Cache. Exporte, Originale in anderen Diensten und Systemsicherungen sind separat zu verwalten. Das Löschen in der App verlangt keine sofortige Löschung beim Umwandlungsanbieter; dessen Fristen gelten. Für Hilfe schreibe uns zunächst ohne die ganze Präsentation anzuhängen.'],
    ['Support','Bei einer Support- oder Datenschutzanfrage erhalten wir Adresse, Nachricht und freiwillige Anhänge und nutzen sie zur Bearbeitung. Bitte sende keine unnötigen persönlichen Daten.'],
    ['Kinder','Die App ist für Personen ab 13 Jahren und nicht für Jüngere bestimmt. Falls ein Kind Daten übermittelt hat, kontaktiere uns; lokale Regeln zur Beteiligung der Eltern gelten weiter.'],
    ['Sicherheit und Änderungen','Die Online-Umwandlung nutzt HTTPS. Dies ist keine Ende-zu-Ende-Verschlüsselung und verhindert nicht, dass der Anbieter die Datei liest. Sprachausgabe und Sicherungen haben eigene Einstellungen. Bei Änderungen der Verarbeitung aktualisieren wir diese Erklärung und geben nötige Hinweise oder Einwilligungsoptionen.'],
    ['Diese Website','GitHub Pages hostet die Seiten und kann übliche Protokolle führen. Cloudflare Web Analytics misst Besuche, Herkunft und Leistung ohne Analyse-Cookies oder websiteübergreifendes Tracking; Präsentationen und App-Wiedergabe werden nicht erfasst.']
  ]},
  harmonyPrivacy:{title:'Datenschutzerklärung für HarmonyOS',intro:'Lokale Verarbeitung von PPTX-Dateien und Notizen in Tingbo für HarmonyOS.',sections:[
    ['Überblick','Die App importiert PPTX, zeigt Folien und liest Notizen vor. Es ist kein Konto nötig; Dateien, Folien und Notizen werden nur auf dem Gerät verarbeitet und nicht an unsere oder fremde Server hochgeladen.'],
    ['Erhobene Daten','Die App erhebt, speichert oder überträgt weder Namen, Telefonnummern, E-Mails, Gerätekennungen, Standorte, Kontakte, Werbe-IDs, Nutzungsverhalten noch Präsentationsinhalte; sie enthält keine Werbung, Analyse oder Tracker.'],
    ['Lokale Dateien','Nur eine über die System-Dateiauswahl aktiv gewählte PPTX-Datei wird gelesen. Entpacken und Auswerten von Bildern und Notizen erfolgen lokal. Datei, Ergebnisse und bearbeitete Notizen bleiben im App-Speicher.'],
    ['Offline-Sprachausgabe','Die Notizen werden mit der Offline-Sprachausgabe von HarmonyOS Core Speech Kit auf dem Gerät gesprochen. Weder Text noch erzeugtes Audio gehen an unsere oder fremde Server.'],
    ['Netzwerk und Dritte','Die App fordert keine Internetberechtigung an und bietet weder Cloud-Umwandlung, Online-Sprachausgabe noch andere Dienste zum Hochladen von Inhalten.'],
    ['Aufbewahrung und Löschung','Präsentationen lassen sich im Verlauf löschen. Bei Deinstallation werden die auf dem Gerät gespeicherten App-Daten entfernt.'],
    ['Kinder','Die App richtet sich nicht speziell an Kinder unter 14 Jahren und erhebt wissentlich keine personenbezogenen Daten von ihnen.'],
    ['Änderungen','Bei Änderungen aktualisieren wir diese Seite und das Datum der letzten Änderung.'],
    ['Kontakt','Fragen an m15568817011@163.com.'],
    ['Website-Analyse','GitHub Pages kann übliche Serverprotokolle führen. Cloudflare Web Analytics misst Besuche und Leistung ohne Analyse-Cookies oder websiteübergreifendes Tracking. Nur die Website ist betroffen; die HarmonyOS-App erhält keinen Internetzugriff und sendet keine Dateien, Notizen oder Audiodaten.']
  ]}
};
