export const ptBR = {
  nav:{navigation:'Navegação principal',language:'Escolher idioma',skip:'Ir para o conteúdo',home:'Início',features:'Recursos',allFeatures:'Ver todos os recursos',notes:'Guia das notas',rehearsal:'Ensaiar',privacy:'Privacidade',terms:'Termos de uso',support:'Contato',download:'Baixar na App Store',originalVersion:'Versão original'},
  home:{eyebrow:'Tingbo · Suas notas em voz alta',title:'Ouça seu roteiro antes de apresentar',description:'Tingbo lê as notas de cada slide, avança automaticamente e permite visualizar PPT, PPTX e Keynote no celular.',intro:'Ouça as notas slide por slide. Ao terminar, o próximo slide pode aparecer automaticamente; a reprodução continua com a tela bloqueada. Edite frases que não soam bem e escute de novo.',formats:'iPhone e iPad · PPT, PPTX e Keynote · Sem conta',featureEyebrow:'Ouça, ajuste, repita',featureTitle:'Ensaie a apresentação, slide por slide',featureIntro:'Escute o roteiro na ordem da apresentação e encontre os trechos a melhorar.',readerEyebrow:'Leitor leve de slides',readerTitle:'Veja os slides enquanto escuta',readerText:'Deslize para navegar, gire o aparelho e amplie detalhes. Notas e controles de áudio continuam à mão.',screenshotAlt:'Tela do Tingbo com slide, notas e controles de áudio em inglês',screenshotCaption:'Exemplo do aplicativo (interface em inglês).',stepsTitle:'Ensaie em três passos',faqTitle:'Perguntas frequentes',ctaTitle:'Domine seu roteiro antes de falar',ctaText:'Importe uma apresentação e comece a ouvir.'},
  features:[['Notas lidas slide por slide','A voz do dispositivo lê as notas do slide exibido, mantendo imagem e roteiro sincronizados.'],['Avanço automático','Depois de cada nota, o próximo slide aparece. Você também pode pausar, repetir ou mudar manualmente.'],['Áudio em segundo plano','Continue ouvindo com a tela bloqueada ou fones; a reprodução pausa se os fones forem desconectados.'],['Edite durante o ensaio','Abra as notas, ajuste uma frase, salve e ouça novamente.'],['Leitor móvel de slides','Deslize, mude a orientação e amplie gráficos e detalhes.'],['Histórico e exportação','Reabra apresentações importadas e exporte notas em Markdown ou uma cópia PPTX, quando disponível.']],
  featuresPage:{title:'Recursos do Tingbo',intro:'Slides, notas e áudio na mesma tela para ensaiar sem perder o ritmo.',formatsTitle:'Arquivos e dispositivos',formatsText:'No iOS 1.2 ou posterior, importe .ppt, .pptx e .key. Disponível para iPhone e iPad. Layouts complexos podem ter aparência diferente conforme o arquivo.'},
  notes:{title:'Como ouvir as notas da apresentação',intro:'Escreva o roteiro nas notas de cada slide; o Tingbo vai lê-lo na sequência.',tip:'Se um slide não tiver notas, adicione primeiro o que você quer dizer.',steps:[['Importe o arquivo','Selecione PPT, PPTX ou Keynote (.key) em Arquivos e confira slides e notas.'],['Inicie a reprodução','Ouça as notas do slide atual; o próximo pode abrir automaticamente ao terminar.'],['Ajuste e repita','Edite frases pouco naturais, salve e reproduza o slide outra vez.']]},
  rehearsal:{title:'Ensaie ouvindo sua apresentação',intro:'Ouvir seu próprio texto ajuda a perceber frases, ordem e transições que precisam de ajuste.',tip:'Faça ao menos uma audição completa antes de apresentar e repita os trechos alterados.',steps:[['Prepare o roteiro','Importe a apresentação e complete as notas de cada slide.'],['Ouça do começo ao fim','Verifique se o texto corresponde aos slides.'],['Melhore e ouça de novo','Corrija frases e pontos esquecidos até a fala soar natural.']]},
  faq:[['Qual é a principal função do Tingbo?','Ler em voz alta as notas de cada slide para você ensaiar enquanto vê a apresentação.'],['Quais arquivos são aceitos?','PPT, PPTX e Keynote (.key) no iOS 1.2 ou posterior.'],['Funciona em segundo plano?','Sim, inclusive com a tela bloqueada; a reprodução pausa quando os fones são desconectados.']],
  privacy:{title:'Política de privacidade do iOS',intro:'Como apresentações, notas e visitas ao site são tratadas.',sections:[
    ['Visão geral','O Tingbo lê notas slide por slide. Apresentações e notas ficam no dispositivo, exceto ao usar o serviço de conversão descrito abaixo. Versões iOS com Firebase usam Firebase Analytics para entender o uso dos recursos; nossos eventos personalizados não incluem nomes de arquivos nem o texto das notas.'],
    ['Dados que não coletamos','Não é preciso criar uma conta. No uso normal, não pedimos nome, e-mail nem acesso aos contatos ou fotos. Eventos de análise personalizados não incluem apresentações, nomes de arquivos ou texto das notas. A conversão na nuvem pode enviar o arquivo escolhido; Firebase Analytics processa eventos de uso e dados técnicos relacionados.'],
    ['Processamento no dispositivo','Apresentações importadas, imagens dos slides e notas ficam no armazenamento local do app. A leitura usa a síntese de voz integrada do iOS.'],
    ['Conversão de apresentações','Para exibir PPT ou PPTX como imagens, algumas versões podem converter o arquivo. É possível usar um serviço na sua rede local; quando é necessária conversão remota, a versão iOS descrita aqui cria a tarefa via Cloudflare Worker e envia o arquivo escolhido diretamente ao CloudConvert. O arquivo serve apenas à conversão solicitada, não a anúncios ou perfis pessoais.'],
    ['Terceiros','Na conversão remota, a Cloudflare processa a solicitação e a CloudConvert recebe o arquivo para gerar o resultado. Não vendemos nem alugamos seus dados. O site é hospedado no GitHub Pages, que pode processar registros de conexão como IP segundo sua política.'],
    ['Análise do app e do site','Versões iOS com Firebase usam Firebase Analytics para registrar formato e origem da importação, resultado e duração da renderização, quantidade de slides, navegação e início da leitura. Eventos personalizados não incluem nomes de arquivos, apresentações ou texto das notas. Firebase também pode coletar eventos automáticos e identificadores do dispositivo ou da instância do app. Separadamente, Cloudflare Web Analytics mede visitas e desempenho do site sem cookies de análise nem rastreamento individual entre sites; não acessa conteúdo do app.'],
    ['Retenção e exclusão','As apresentações permanecem no espaço local do app. Você pode apagar cada uma no histórico; desinstalar o app remove os dados que ele guarda no dispositivo.'],
    ['Crianças','O app não é direcionado a menores de 13 anos e não coletamos intencionalmente informações pessoais de crianças.'],
    ['Alterações','Podemos atualizar esta política e indicar uma nova data. Continuar usando o app após a entrada em vigor significa aceitar a versão atualizada.'],
    ['Contato','Dúvidas sobre privacidade: m15568817011@163.com.']
  ]},
  terms:{title:'Termos de uso do iOS',intro:'Leia estes termos antes de usar o Tingbo para iOS.',sections:[
    ['Aceitação','Ao baixar, instalar ou usar o Tingbo, você aceita estes termos. Caso discorde, não use o app.'],
    ['Licença','Sujeita a estes termos e aos da Apple App Store, concedemos licença limitada, não exclusiva, intransferível e revogável para uso pessoal e não comercial nos seus dispositivos Apple.'],
    ['Seu conteúdo','Você mantém os direitos sobre apresentações e notas importadas e é responsável por ter autorização para usá-las e processá-las.'],
    ['Como funciona','O app exibe slides como imagens e lê notas com a voz do dispositivo. A conversão pode ocorrer na sua rede local ou, se você configurar um serviço remoto, o arquivo escolhido pode ser processado por terceiros apenas para a conversão solicitada. Veja a política de privacidade.'],
    ['Uso permitido','Não faça engenharia reversa, descompilação ou desmontagem; não use o app ilegalmente nem o copie, venda, alugue, sublicencie ou distribua; não importe conteúdo sem direito de uso.'],
    ['Serviços de terceiros','Fornecedores de conversão remota podem processar arquivos para gerar imagens de slides. Hospedagem do site e outros serviços possuem termos e políticas próprios.'],
    ['Propriedade intelectual','Design, código, imagens e demais elementos do app pertencem a nós ou aos licenciadores e são protegidos por lei. Nenhum outro direito é concedido.'],
    ['Isenção de garantias','O app é fornecido “no estado em que se encontra” e “conforme disponível”, sem garantias expressas ou implícitas de comerciabilidade, adequação ou não violação. Não garantimos operação ininterrupta, sem erros ou segurança absoluta.'],
    ['Limitação de responsabilidade','No limite permitido por lei, não respondemos por danos indiretos, incidentais, especiais, consequenciais ou punitivos, nem por perda de lucros ou dados decorrente do uso, mesmo se avisados da possibilidade.'],
    ['Encerramento','Você pode parar de usar o app a qualquer momento. Podemos suspender ou encerrar a licença por violação; nesse caso, pare de usar e remova o app do dispositivo.'],
    ['Alterações','Podemos publicar termos atualizados com nova data. O uso após a entrada em vigor significa aceitação.'],
    ['Lei aplicável','Aplicam-se as leis do seu país ou região de residência, sem restringir direitos obrigatórios do consumidor.'],
    ['Contato','Dúvidas: m15568817011@163.com.']
  ]},
  androidPrivacy:{title:'Política de privacidade do Android',intro:'Tratamento de arquivos, voz e dados no Tingbo para Android, destinado a pessoas com 13 anos ou mais.',sections:[
    ['Arquivos e dados locais','Após importar pelo seletor do Android, o app guarda localmente uma cópia de trabalho, slides, nome e data de importação, notas alteradas, histórico, preferências e caches de áudio e exportação. Arquivos exportados vão para o local escolhido, que pode ser um serviço em nuvem.'],
    ['Conversão on-line','Se for necessária conversão ou renderização on-line, toda a apresentação escolhida é enviada, possivelmente com texto, imagens, notas e objetos incorporados. O arquivo original passa por Cloudflare Worker até CloudConvert e o resultado volta pelo Worker. A CloudConvert informa exclusão automática de tarefas e dados 24 horas após a conclusão; sua política menciona registros de IP, User-Agent, horário e estatísticas por até 180 dias. A Cloudflare também pode tratar dados de rede e solicitação; fornecedores podem operar fora do país.'],
    ['Síntese de voz do Android','As notas são entregues ao motor de voz ativo no dispositivo. Ao abrir, trocar de slide ou editar, o texto do slide atual e dos próximos pode ser preparado antes de tocar em reproduzir. O uso totalmente off-line depende do motor, voz e ajustes; vozes on-line podem enviar texto e dados da solicitação ao fornecedor. Você pode trocar o motor nas configurações do sistema.'],
    ['Backup e transferência','Se habilitados, Android ou fabricante podem copiar, transferir ou restaurar dados elegíveis do app, incluindo apresentações e preferências, conforme versão, conta e ajustes. Isso é separado do serviço de conversão.'],
    ['Retenção e exclusão','Apagar uma apresentação do histórico remove a cópia local, notas editadas e registro, mas talvez não todos os caches de voz ou exportação. Gerencie separadamente exportações, originais em outros serviços e backups do sistema. A exclusão no app não pede exclusão imediata ao fornecedor de conversão; valem os prazos dele. Para obter ajuda, escreva primeiro sem anexar a apresentação completa.'],
    ['Suporte','Ao escrever para suporte ou fazer pedido de privacidade, recebemos seu endereço, mensagem e anexos enviados voluntariamente para responder. Evite compartilhar dados desnecessários.'],
    ['Crianças','O app destina-se a pessoas com 13 anos ou mais, não a menores. Se uma criança enviou dados, contate-nos; regras locais de participação dos responsáveis continuam valendo.'],
    ['Segurança e alterações','A conversão usa HTTPS, que não é criptografia de ponta a ponta e não impede o fornecedor de ler o arquivo. Motor de voz e backups têm seus próprios ajustes. Atualizaremos a política quando o tratamento mudar e daremos avisos ou opções de consentimento necessários.'],
    ['Este site','GitHub Pages hospeda as páginas e pode manter registros comuns. Cloudflare Web Analytics mede visitas, origem e desempenho sem cookies de análise ou rastreamento entre sites; não analisa apresentações nem reprodução no app.']
  ]},
  harmonyPrivacy:{title:'Política de privacidade do HarmonyOS',intro:'Como o Tingbo para HarmonyOS trata arquivos PPTX e notas no dispositivo.',sections:[
    ['Visão geral','O app importa PPTX, mostra slides e lê notas. Não exige conta; arquivo, slides e notas são processados só no dispositivo, sem envio a servidores nossos ou de terceiros.'],
    ['Dados coletados','O app não coleta, guarda ou envia nome, telefone, e-mail, identificadores, localização, contatos, IDs de publicidade, atividade ou conteúdo de apresentações; não integra anúncios, análises ou rastreadores.'],
    ['Arquivos locais','Apenas o PPTX escolhido no seletor do sistema é lido. Descompactação e análise de imagens e notas ocorrem localmente. Arquivo, resultados e notas editadas ficam no armazenamento local do app.'],
    ['Voz off-line','A leitura usa a síntese de voz off-line do HarmonyOS Core Speech Kit. Texto das notas e áudio gerado não são enviados a nossos servidores ou terceiros.'],
    ['Rede e terceiros','O app não solicita permissão de Internet nem oferece conexão, conversão em nuvem, voz on-line ou serviço que envie seu conteúdo.'],
    ['Retenção e exclusão','Você pode apagar apresentações no histórico. Desinstalar o app remove os dados que ele guarda no dispositivo.'],
    ['Crianças','O app não é destinado especificamente a menores de 14 anos e não coleta intencionalmente seus dados pessoais.'],
    ['Alterações','Se esta política mudar, atualizaremos a página e a data de revisão.'],
    ['Contato','Dúvidas: m15568817011@163.com.'],
    ['Análise do site','GitHub Pages pode manter registros comuns. Cloudflare Web Analytics mede visitas e desempenho sem cookies de análise ou rastreamento entre sites. Isso vale só para o site: não dá acesso à Internet ao app HarmonyOS nem envia arquivos, notas ou áudio.']
  ]}
};

export const ru = {
  nav:{navigation:'Основная навигация',language:'Выбрать язык',skip:'К содержимому',home:'Главная',features:'Возможности',allFeatures:'Все возможности',notes:'Как слушать заметки',rehearsal:'Репетиция',privacy:'Конфиденциальность',terms:'Условия использования',support:'Связаться с нами',download:'Загрузить в App Store',originalVersion:'Исходная версия'},
  home:{eyebrow:'Tingbo · Заметки к слайдам вслух',title:'Слушайте свой текст и выступайте увереннее',description:'Tingbo озвучивает заметки к каждому слайду, переключает слайды автоматически и открывает PPT, PPTX и Keynote на телефоне.',intro:'Слушайте заметки к слайдам по порядку. После чтения приложение может перейти к следующему слайду; звук продолжится и при заблокированном экране. Исправляйте неудобные фразы и слушайте снова.',formats:'iPhone и iPad · PPT, PPTX, Keynote · Без учётной записи',featureEyebrow:'Слушайте, исправляйте, повторяйте',featureTitle:'Репетируйте выступление с первого слайда',featureIntro:'Слушайте сценарий в порядке презентации и находите места, которые стоит улучшить.',readerEyebrow:'Лёгкий просмотр слайдов',readerTitle:'Смотрите слайды во время прослушивания',readerText:'Листайте, поворачивайте экран и увеличивайте детали. Заметки и управление звуком всегда рядом.',screenshotAlt:'Экран Tingbo со слайдом, заметками и управлением звуком на английском языке',screenshotCaption:'Пример экрана приложения (английский интерфейс).',stepsTitle:'Три шага для репетиции',faqTitle:'Частые вопросы',ctaTitle:'Выучите сценарий перед выступлением',ctaText:'Импортируйте презентацию и начните слушать.'},
  features:[['Озвучивание заметок по слайдам','Системный синтез речи читает заметки к текущему слайду, сохраняя связь текста и изображения.'],['Автоматический переход','После озвучивания открывается следующий слайд. Можно остановить, повторить или перелистнуть вручную.'],['Звук в фоне','Слушайте при заблокированном экране или в наушниках; при отключении наушников воспроизведение приостанавливается.'],['Правьте текст во время репетиции','Откройте заметки, исправьте фразу, сохраните и послушайте ещё раз.'],['Просмотр на телефоне','Листайте, меняйте ориентацию и увеличивайте графики и детали.'],['История и экспорт','Повторно открывайте импортированные презентации; экспортируйте заметки в Markdown или копию PPTX, если доступно.']],
  featuresPage:{title:'Возможности Tingbo',intro:'Слайды, заметки и озвучивание на одном экране — для непрерывной репетиции.',formatsTitle:'Файлы и устройства',formatsText:'iOS версии 1.2 и новее импортирует .ppt, .pptx и .key. Доступно на iPhone и iPad. Сложная вёрстка может отображаться по-разному в зависимости от файла.'},
  notes:{title:'Как озвучить заметки к презентации',intro:'Запишите свой сценарий в заметках к каждому слайду — Tingbo прочитает их по порядку.',tip:'Если у слайда нет заметок, сначала добавьте то, что хотите сказать.',steps:[['Импортируйте файл','Выберите PPT, PPTX или Keynote (.key) в «Файлах» и проверьте слайды и заметки.'],['Начните воспроизведение','Послушайте текст текущего слайда; после окончания возможен автоматический переход.'],['Исправьте и повторите','Измените неудачную фразу, сохраните и прослушайте этот слайд снова.']]},
  rehearsal:{title:'Репетируйте, слушая презентацию',intro:'Прослушивание помогает заметить проблемы с формулировками, порядком и переходами.',tip:'Перед выступлением послушайте весь материал хотя бы раз и повторите исправленные места.',steps:[['Подготовьте заметки','Импортируйте презентацию и заполните заметки к каждому слайду.'],['Прослушайте всё подряд','Проверьте, совпадает ли текст с показанными слайдами.'],['Улучшите и повторите','Исправьте фразы и пропуски, пока речь не станет естественной.']]},
  faq:[['Для чего нужен Tingbo?','Он читает заметки к каждому слайду, помогая репетировать во время просмотра презентации.'],['Какие файлы поддерживаются?','PPT, PPTX и Keynote (.key) в iOS 1.2 и новее.'],['Можно ли слушать в фоне?','Да, и при заблокированном экране; при отключении наушников воспроизведение приостанавливается.']],
  privacy:{title:'Политика конфиденциальности iOS',intro:'Как обрабатываются презентации, заметки и посещения сайта.',sections:[
    ['Обзор','Tingbo озвучивает заметки к слайдам. Презентации и заметки хранятся на устройстве, кроме случаев использования описанного ниже сервиса преобразования. Версии iOS с Firebase используют Firebase Analytics для анализа функций; наши пользовательские события не содержат имён файлов или текста заметок.'],
    ['Какие данные мы не собираем','Учётная запись не нужна. При обычном использовании мы не запрашиваем имя, электронную почту или доступ к контактам и фотографиям. Пользовательские аналитические события не содержат презентаций, имён файлов или текста заметок. При облачном преобразовании выбранный файл может передаваться; Firebase Analytics обрабатывает события использования и связанные технические данные.'],
    ['Обработка на устройстве','Импортированные презентации, изображения слайдов и заметки хранятся локально в приложении. Для чтения используется встроенный синтез речи iOS.'],
    ['Преобразование презентаций','Для отображения PPT/PPTX как изображений некоторые версии могут преобразовывать файл. Можно использовать службу в своей локальной сети; если нужен удалённый сервис, описанная здесь версия iOS создаёт задачу через Cloudflare Worker и отправляет выбранный файл напрямую в CloudConvert. Файл используется только для запрошенного преобразования, не для рекламы или профилирования.'],
    ['Сторонние сервисы','При удалённом преобразовании Cloudflare обрабатывает запрос, а CloudConvert получает файл и создаёт результат. Мы не продаём и не сдаём данные в аренду. Сайт размещён на GitHub Pages, который может обрабатывать обычные журналы соединений, например IP-адреса, по своей политике.'],
    ['Аналитика приложения и сайта','Версии iOS с Firebase используют Firebase Analytics для записи формата и источника импорта, результата и длительности отображения, числа слайдов, переключений и начала озвучивания. Пользовательские события не содержат имён файлов, презентаций или текста заметок. Firebase также может собирать автоматические события и идентификаторы устройства или экземпляра приложения. Отдельно Cloudflare Web Analytics измеряет посещения и работу сайта без аналитических cookie и отслеживания людей между сайтами; содержимое приложения ему недоступно.'],
    ['Хранение и удаление','Презентации остаются в локальном пространстве приложения. Вы можете удалять их в истории; удаление приложения стирает сохранённые им на устройстве данные.'],
    ['Дети','Приложение не предназначено для детей младше 13 лет; мы сознательно не собираем их личные данные.'],
    ['Изменения','Мы можем обновлять политику с новой датой. Продолжение использования после вступления изменений в силу означает согласие.'],
    ['Контакт','Вопросы о конфиденциальности: m15568817011@163.com.']
  ]},
  terms:{title:'Условия использования iOS',intro:'Прочитайте эти условия перед использованием Tingbo для iOS.',sections:[
    ['Согласие','Скачивая, устанавливая или используя Tingbo, вы соглашаетесь с условиями. Если вы не согласны, не пользуйтесь приложением.'],
    ['Лицензия','При соблюдении этих условий и условий Apple App Store вам предоставляется ограниченная, неисключительная, непередаваемая, отзывная лицензия на личное некоммерческое использование на ваших устройствах Apple.'],
    ['Ваши материалы','Права на импортированные презентации и заметки остаются у вас. Вы должны иметь право использовать и обрабатывать эти материалы.'],
    ['Работа приложения','Слайды показываются как изображения, заметки читает синтез речи устройства. Преобразование может выполняться в вашей локальной сети; при настройке удалённого сервиса выбранный файл может обрабатываться третьей стороной только для запрошенного преобразования. Подробнее — в политике конфиденциальности.'],
    ['Допустимое использование','Не выполняйте обратную разработку, декомпиляцию или разборку; не используйте приложение незаконно, не копируйте, не продавайте, не сдавайте в аренду, не сублицензируйте и не распространяйте его; не импортируйте материалы без разрешения.'],
    ['Сторонние сервисы','Поставщики удалённого преобразования могут обрабатывать файлы для создания изображений слайдов. Хостинг сайта и другие сервисы имеют собственные условия и политики.'],
    ['Интеллектуальная собственность','Дизайн, код, изображения и другие элементы приложения принадлежат нам или лицензиарам и защищены законом. Иных прав эти условия не предоставляют.'],
    ['Отказ от гарантий','Приложение предоставляется «как есть» и «по мере доступности», без явных или подразумеваемых гарантий пригодности для продажи, конкретной цели или ненарушения прав. Мы не обещаем бесперебойность, отсутствие ошибок или абсолютную безопасность.'],
    ['Ограничение ответственности','В максимально разрешённой законом степени мы не отвечаем за косвенные, случайные, особые, последующие или штрафные убытки, упущенную прибыль и потерю данных вследствие использования, даже если были предупреждены о риске.'],
    ['Прекращение','Вы можете перестать использовать приложение в любой момент. При нарушении условий мы можем приостановить или прекратить лицензию; тогда следует прекратить использование и удалить приложение.'],
    ['Изменения','Мы можем публиковать новые условия и дату обновления. Продолжение использования после вступления в силу означает согласие.'],
    ['Применимое право','Действует право страны или региона вашего проживания без ограничения обязательных прав потребителя.'],
    ['Контакт','Пишите на m15568817011@163.com.']
  ]},
  androidPrivacy:{title:'Политика конфиденциальности Android',intro:'Обработка файлов, речи и данных в Tingbo для Android; для пользователей от 13 лет.',sections:[
    ['Локальные файлы и данные','После выбора файла средствами Android приложение сохраняет рабочую копию, слайды, имя и время импорта, отредактированные заметки, историю, настройки, кэши речи и экспорта. Экспортированные файлы сохраняются в указанном месте, в том числе в облачном сервисе.'],
    ['Онлайн-преобразование','Если требуется преобразование или отображение онлайн, целая выбранная презентация загружается, включая возможные тексты, изображения, заметки и встроенные объекты. Оригинал проходит через Cloudflare Worker в CloudConvert, а результат возвращается через Worker. CloudConvert заявляет об автоматическом удалении задач и данных через 24 часа после завершения; его политика допускает хранение журналов IP, User-Agent, времени и статистики до 180 дней. Cloudflare также может обрабатывать сетевые данные и сведения о запросе; обработка возможна за рубежом.'],
    ['Синтез речи Android','Текст заметок передаётся активному движку синтеза речи устройства. При открытии, смене слайда или правке текст текущей и соседних страниц может подготавливаться до нажатия кнопки воспроизведения. Полная автономность зависит от движка, голоса и настроек; сетевые голоса могут отправлять текст и данные запроса поставщику. Движок можно сменить в настройках системы.'],
    ['Резервные копии и перенос','Если включены, Android или производитель могут копировать, передавать и восстанавливать подходящие данные приложения, включая презентации и настройки, в зависимости от версии, аккаунта и параметров. Это не связано со службой преобразования.'],
    ['Хранение и удаление','Удаление из истории убирает локальную копию, изменённые заметки и запись, но может не очистить все кэши речи и экспорта. Экспорт, оригиналы у других поставщиков и системные копии нужно удалять отдельно. Удаление в приложении не требует немедленного удаления у поставщика преобразования; действуют его сроки. Для помощи напишите нам, не прикладывая сначала всю презентацию.'],
    ['Поддержка','При обращении в поддержку или по вопросам конфиденциальности мы получаем ваш адрес, сообщение и добровольные вложения, чтобы ответить. Не отправляйте лишние персональные сведения.'],
    ['Дети','Приложение рассчитано на людей от 13 лет, не на детей младше 13. Если ребёнок передал данные, свяжитесь с нами; местные правила участия родителей сохраняются.'],
    ['Безопасность и изменения','Для онлайн-преобразования используется HTTPS, но это не сквозное шифрование и не препятствует поставщику читать файл. У движка речи и резервных копий свои настройки. При изменении обработки мы обновим политику и дадим необходимые уведомления или запросим согласие.'],
    ['Этот сайт','Страницы размещены на GitHub Pages, где возможны обычные журналы соединений. Cloudflare Web Analytics измеряет посещения, источники и производительность без аналитических cookie или межсайтового отслеживания; презентации и воспроизведение в приложении не анализируются.']
  ]},
  harmonyPrivacy:{title:'Политика конфиденциальности HarmonyOS',intro:'Как Tingbo для HarmonyOS обрабатывает PPTX и заметки на устройстве.',sections:[
    ['Обзор','Приложение импортирует PPTX, показывает слайды и озвучивает заметки. Учётная запись не нужна; файл, слайды и заметки обрабатываются только на устройстве и не загружаются на наши или чужие серверы.'],
    ['Сбор данных','Приложение не собирает, не хранит и не отправляет имена, телефоны, адреса почты, идентификаторы, местоположение, контакты, рекламные ID, действия или содержимое презентаций; в нём нет рекламы, аналитики и трекеров.'],
    ['Локальные файлы','Читается только PPTX, который вы выбрали в системном окне. Распаковка и разбор изображений и заметок выполняются локально. Файл, результаты и исправленные заметки остаются в хранилище приложения.'],
    ['Речь без интернета','Для чтения используется автономный синтез речи HarmonyOS Core Speech Kit. Ни текст заметок, ни полученный звук не отправляются на наши или сторонние серверы.'],
    ['Сеть и сторонние службы','Приложение не запрашивает доступ в интернет и не предоставляет облачное преобразование, сетевой голос или другие службы для отправки ваших материалов.'],
    ['Хранение и удаление','Презентации можно удалить из истории. Удаление приложения стирает данные, сохранённые им на устройстве.'],
    ['Дети','Приложение не предназначено специально для детей младше 14 лет; мы сознательно не собираем их личные данные.'],
    ['Изменения','При изменении политики мы обновим страницу и дату редакции.'],
    ['Контакт','Вопросы: m15568817011@163.com.'],
    ['Аналитика сайта','GitHub Pages может сохранять обычные серверные журналы. Cloudflare Web Analytics измеряет посещения и производительность без аналитических cookie или межсайтового отслеживания. Это касается только сайта: HarmonyOS-приложение не получает доступ в интернет и не отправляет файлы, заметки или звук.']
  ]}
};

export const ar = {
  nav:{navigation:'التنقل الرئيسي',language:'اختيار اللغة',skip:'الانتقال إلى المحتوى',home:'الرئيسية',features:'الميزات',allFeatures:'عرض كل الميزات',notes:'دليل قراءة الملاحظات',rehearsal:'التدرب على العرض',privacy:'سياسة الخصوصية',terms:'شروط الاستخدام',support:'اتصل بنا',download:'التنزيل من App Store',originalVersion:'النسخة الأصلية'},
  home:{eyebrow:'Tingbo · استمع إلى ملاحظات العرض',title:'استمع إلى نصك قبل أن تقدّم عرضك',description:'يقرأ Tingbo ملاحظات كل شريحة بصوت عالٍ، وينتقل تلقائيًا، ويعرض ملفات PPT وPPTX وKeynote على الهاتف.',intro:'استمع إلى ملاحظات الشرائح بالترتيب. يمكن الانتقال إلى الشريحة التالية عند انتهاء القراءة، ويستمر الصوت عند قفل الشاشة. عدّل العبارات غير المريحة ثم استمع إليها مجددًا.',formats:'iPhone وiPad · ملفات PPT وPPTX وKeynote · بلا حساب',featureEyebrow:'استمع وعدّل وكرّر',featureTitle:'تدرّب على عرضك شريحة بعد أخرى',featureIntro:'استمع إلى النص وفق ترتيب الشرائح واكتشف ما يحتاج إلى تحسين.',readerEyebrow:'قارئ خفيف للشرائح',readerTitle:'شاهد الشريحة بينما تستمع إلى النص',readerText:'اسحب للتنقل بين الصفحات، وأدر الهاتف وكبّر التفاصيل. تبقى الملاحظات وأزرار الصوت في متناولك.',screenshotAlt:'واجهة Tingbo تعرض شريحة وملاحظات وأزرار صوت باللغة الإنجليزية',screenshotCaption:'صورة توضيحية للتطبيق (واجهة باللغة الإنجليزية).',stepsTitle:'ثلاث خطوات للتدرب',faqTitle:'أسئلة شائعة',ctaTitle:'أتقن نصك قبل الوقوف أمام الجمهور',ctaText:'استورد عرضك وابدأ الاستماع.'},
  features:[['قراءة ملاحظات كل شريحة','يقرأ محرك النطق في الجهاز ملاحظات الشريحة المعروضة ليبقى النص والصورة متزامنين.'],['الانتقال التلقائي','بعد انتهاء قراءة الملاحظات، تظهر الشريحة التالية. يمكنك الإيقاف أو الإعادة أو التنقل يدويًا.'],['الصوت في الخلفية','تابع الاستماع عند قفل الشاشة أو عبر سماعات الأذن؛ يتوقف الصوت مؤقتًا عند فصلها.'],['تعديل النص أثناء التدريب','افتح الملاحظات، وعدّل العبارة، واحفظها ثم استمع من جديد.'],['عرض الشرائح على الهاتف','اسحب، وغيّر اتجاه الشاشة، وكبّر الرسوم والتفاصيل.'],['السجل والتصدير','أعد فتح العروض المستوردة، وصدّر الملاحظات بصيغة Markdown أو نسخة PPTX عند توفرها.']],
  featuresPage:{title:'ميزات Tingbo',intro:'الشرائح والملاحظات والصوت في شاشة واحدة لتتدرب دون انقطاع.',formatsTitle:'الملفات والأجهزة',formatsText:'يدعم إصدار iOS 1.2 وما بعده استيراد ملفات .ppt و.pptx و.key على iPhone وiPad. قد يختلف عرض التنسيقات المعقدة بحسب الملف.'},
  notes:{title:'كيفية الاستماع إلى ملاحظات العرض',intro:'اكتب نصك في ملاحظات كل شريحة ليقرأه Tingbo بالترتيب.',tip:'إذا لم تتضمن الشريحة ملاحظات، فأضف ما تريد قوله قبل تشغيل القراءة.',steps:[['استورد العرض','اختر ملف PPT أو PPTX أو Keynote ‏(.key) من الملفات، وتحقق من الشرائح والملاحظات.'],['شغّل القراءة','استمع إلى نص الشريحة الحالية؛ ويمكن الانتقال إلى التالية تلقائيًا بعد انتهائه.'],['عدّل واستمع مجددًا','صحّح العبارات غير الطبيعية، واحفظ التغييرات وأعد تشغيل الشريحة.']]},
  rehearsal:{title:'تدرّب بالاستماع إلى عرضك',intro:'يساعد سماع النص على اكتشاف مشكلات الصياغة والترتيب والانتقال بين الشرائح.',tip:'استمع إلى العرض كاملًا مرة واحدة على الأقل قبل تقديمه، ثم كرّر المقاطع التي عدّلتها.',steps:[['حضّر النص','استورد العرض وأكمل ملاحظات كل شريحة.'],['استمع من البداية للنهاية','تأكد من توافق الكلام مع الشرائح المعروضة.'],['حسّن وكرّر','صحّح العبارات والنقاط الناقصة حتى يبدو الكلام طبيعيًا.']]},
  faq:[['ما وظيفة Tingbo الأساسية؟','قراءة ملاحظات كل شريحة لتتدرب بينما تشاهد العرض.'],['ما الملفات المدعومة؟','PPT وPPTX وKeynote ‏(.key) في iOS 1.2 وما بعده.'],['هل يعمل الصوت في الخلفية؟','نعم، حتى عند قفل الشاشة؛ ويتوقف مؤقتًا عند فصل سماعات الأذن.']],
  privacy:{title:'سياسة خصوصية iOS',intro:'كيفية التعامل مع العروض والملاحظات وزيارات هذا الموقع.',sections:[
    ['نظرة عامة','يقرأ Tingbo ملاحظات الشرائح. تُحفظ العروض والملاحظات على جهازك، باستثناء استخدام خدمة التحويل الموضحة أدناه. تستخدم إصدارات iOS المزوّدة بـ Firebase خدمة Firebase Analytics لفهم استخدام الميزات؛ ولا تتضمن أحداثنا المخصصة أسماء الملفات أو نص الملاحظات.'],
    ['بيانات لا نجمعها','لا يلزم إنشاء حساب. أثناء الاستخدام العادي لا نطلب الاسم أو البريد الإلكتروني أو الوصول إلى جهات الاتصال أو الصور. لا تتضمن أحداث التحليل المخصصة العروض أو أسماء الملفات أو نص الملاحظات. قد يُرسل الملف المختار عند التحويل السحابي؛ وتعالج Firebase Analytics أحداث الاستخدام والبيانات التقنية المرتبطة بها.'],
    ['المعالجة على الجهاز','تُحفظ العروض المستوردة وصور الشرائح والملاحظات في مساحة التطبيق المحلية. تستخدم القراءة ميزة تحويل النص إلى كلام المدمجة في iOS.'],
    ['تحويل العروض','لعرض PPT أو PPTX كصور، قد تحوّل بعض الإصدارات الملف. يمكن استخدام خدمة ضمن شبكتك المحلية؛ وعند الحاجة إلى تحويل بعيد، ينشئ إصدار iOS الموصوف هنا مهمة عبر Cloudflare Worker ويرفع الملف المختار مباشرة إلى CloudConvert. يُستخدم الملف للتحويل المطلوب فقط، لا للإعلان أو إنشاء ملفات تعريف شخصية.'],
    ['خدمات الأطراف الأخرى','في التحويل البعيد تعالج Cloudflare الطلب وتتلقى CloudConvert الملف لإنتاج النتيجة. لا نبيع بياناتك أو نؤجرها. يستضيف GitHub Pages الموقع وقد يعالج سجلات الاتصال المعتادة مثل عنوان IP وفق سياسته.'],
    ['تحليلات التطبيق والموقع','تستخدم إصدارات iOS المزوّدة بـ Firebase خدمة Firebase Analytics لتسجيل صيغة الملف ومصدر الاستيراد ونتيجة العرض ومدته وعدد الشرائح والتنقل وبدء القراءة. لا تتضمن الأحداث المخصصة أسماء الملفات أو العروض أو نص الملاحظات. قد تجمع Firebase أيضًا أحداث التطبيق التلقائية ومعرّفات الجهاز أو نسخة التطبيق. وبشكل منفصل، تقيس Cloudflare Web Analytics زيارات الموقع وأداءه بلا ملفات تعريف ارتباط للتحليلات أو تتبع الأفراد عبر المواقع؛ ولا يمكنها الوصول إلى محتوى التطبيق.'],
    ['الاحتفاظ والحذف','تبقى العروض في مساحة التطبيق المحلية. يمكنك حذف كل عرض من السجل؛ وإزالة التطبيق تحذف محتواه المخزن على الجهاز.'],
    ['خصوصية الأطفال','التطبيق غير موجّه لمن هم دون 13 عامًا، ولا نجمع عن علم معلوماتهم الشخصية.'],
    ['التغييرات','قد نحدّث هذه السياسة مع تاريخ جديد. استمرار استخدام التطبيق بعد سريان التغييرات يعني قبولها.'],
    ['الاتصال','للأسئلة حول الخصوصية: m15568817011@163.com.']
  ]},
  terms:{title:'شروط استخدام iOS',intro:'يرجى قراءة هذه الشروط قبل استخدام Tingbo على iOS.',sections:[
    ['القبول','يعني تنزيل Tingbo أو تثبيته أو استخدامه قبولك لهذه الشروط. إن لم توافق، فلا تستخدم التطبيق.'],
    ['الترخيص','مع الالتزام بهذه الشروط وشروط Apple App Store، نمنحك ترخيصًا محدودًا وغير حصري وغير قابل للنقل وقابلًا للإلغاء للاستخدام الشخصي غير التجاري على أجهزة Apple الخاصة بك.'],
    ['محتواك','تحتفظ بحقوقك في العروض والملاحظات المستوردة، وتتحمل مسؤولية امتلاك حق استخدامها ومعالجتها.'],
    ['طريقة العمل','يعرض التطبيق الشرائح كصور ويقرأ الملاحظات بصوت الجهاز. قد يتم التحويل في شبكتك المحلية؛ وإذا أعددت خدمة بعيدة فقد يعالج طرف ثالث الملف المختار للتحويل المطلوب فقط. راجع سياسة الخصوصية.'],
    ['الاستخدام المسموح','لا تفكك التطبيق أو تجري هندسة عكسية أو تفك شفرتَه؛ ولا تستخدمه بصورة غير قانونية أو تنسخه أو تبيعه أو تؤجره أو تمنح ترخيصًا فرعيًا له أو توزعه؛ ولا تستورد محتوى بلا إذن.'],
    ['خدمات الأطراف الأخرى','قد تعالج خدمات التحويل البعيد الملفات لإنتاج صور الشرائح. وللاستضافة وغيرها شروط وسياسات مستقلة.'],
    ['الملكية الفكرية','تصميم التطبيق ورمزه وصوره ومحتواه ملك لنا أو لمرخّصينا وتحميه القوانين. لا تُمنح حقوق أخرى.'],
    ['إخلاء المسؤولية','يُقدّم التطبيق «كما هو» و«حسب التوفر» بلا ضمانات صريحة أو ضمنية، بما فيها الملاءمة التجارية أو لغرض معين أو عدم انتهاك الحقوق. لا نضمن استمرارية الخدمة أو خلوها من الأخطاء أو أمانها المطلق.'],
    ['حدود المسؤولية','إلى أقصى حد يسمح به القانون، لا نتحمل الأضرار غير المباشرة أو العرضية أو الخاصة أو اللاحقة أو العقابية، ولا خسارة الأرباح أو البيانات الناجمة عن الاستخدام، حتى لو أُبلغنا بإمكان وقوعها.'],
    ['الإنهاء','يمكنك التوقف عن الاستخدام متى شئت. قد نعلّق الترخيص أو ننهيه عند مخالفة الشروط؛ وعندها يجب إيقاف الاستخدام وإزالة التطبيق من الجهاز.'],
    ['تغيير الشروط','قد ننشر شروطًا محدّثة بتاريخ جديد. يعني الاستمرار في الاستخدام بعد سريانها قبولها.'],
    ['القانون الواجب التطبيق','تسري قوانين بلد أو منطقة إقامتك دون تقييد حقوق المستهلك الإلزامية.'],
    ['الاتصال','للأسئلة: m15568817011@163.com.']
  ]},
  androidPrivacy:{title:'سياسة خصوصية Android',intro:'معالجة الملفات والصوت والبيانات في Tingbo لنظام Android؛ للمستخدمين بعمر 13 عامًا فأكثر.',sections:[
    ['الملفات والبيانات المحلية','بعد الاستيراد عبر منتقي ملفات Android، يحتفظ التطبيق محليًا بنسخة عمل وشرائح واسم الملف ووقت الاستيراد والملاحظات المعدّلة والسجل والتفضيلات وذاكرات الصوت والتصدير المؤقتة. تُحفظ الملفات المصدّرة في المكان الذي تختاره، وقد يكون خدمة سحابية.'],
    ['التحويل عبر الإنترنت','عند الحاجة إلى تحويل أو عرض عبر الإنترنت، يُرفع العرض المختار كاملًا وقد يضم نصًا وصورًا وملاحظات وعناصر مضمنة. ينتقل الأصل عبر Cloudflare Worker إلى CloudConvert وتعود النتيجة عبر Worker. تقول CloudConvert إنها تحذف المهام والبيانات تلقائيًا بعد 24 ساعة من إتمامها؛ وتشير سياستها إلى إمكان الاحتفاظ بسجلات IP وUser-Agent والوقت والإحصاءات مدة 180 يومًا. قد تعالج Cloudflare بيانات الشبكة والطلب، وقد تتم المعالجة خارج بلدك.'],
    ['تحويل النص إلى كلام في Android','تُسلّم الملاحظات إلى محرك النطق المفعّل في الجهاز. عند فتح العرض أو تبديل الشريحة أو تحريرها، قد يُحضّر نص الصفحة الحالية والصفحات المجاورة قبل الضغط على تشغيل. تعتمد إمكانية العمل دون إنترنت على المحرك والصوت والإعدادات؛ وقد ترسل الأصوات الشبكية النص وبيانات الطلب إلى مزوّدها. يمكنك تغيير المحرك في إعدادات النظام.'],
    ['النسخ الاحتياطي والنقل','إذا كانا مفعّلين، قد ينسخ Android أو صانع الجهاز بيانات التطبيق المؤهلة أو ينقلها أو يستعيدها، بما فيها العروض والتفضيلات، وفق الإصدار والحساب والإعدادات. هذا منفصل عن خدمة التحويل.'],
    ['الاحتفاظ والحذف','حذف عرض من السجل يزيل نسخته المحلية وملاحظاته المعدّلة وسجله، لكنه قد لا يمحو كل ذواكر الصوت أو التصدير المؤقتة. أدر الملفات المصدّرة والأصول في خدمات أخرى ونسخ النظام الاحتياطية بشكل مستقل. الحذف داخل التطبيق لا يطلب حذفًا فوريًا من مزوّد التحويل؛ تسري مدد احتفاظه. للمساعدة، راسلنا دون إرفاق العرض كاملًا في البداية.'],
    ['الدعم','عند مراسلة الدعم أو إرسال طلب خصوصية نتلقى عنوانك ورسالتك والمرفقات التي ترسلها باختيارك للرد عليك. تجنب إرسال بيانات شخصية غير لازمة.'],
    ['الأطفال','التطبيق لمن هم بعمر 13 عامًا فأكثر وليس لمن هم أصغر. إذا أرسل طفل بيانات، اتصل بنا؛ وتظل قواعد مشاركة الوالدين المحلية سارية.'],
    ['الأمان والتغييرات','يستخدم التحويل HTTPS، لكنه ليس تشفيرًا شاملًا بين الطرفين ولا يمنع مزوّد التحويل من قراءة الملف. لمحرك النطق والنسخ الاحتياطي إعداداتهما الخاصة. سنحدّث السياسة عند تغير المعالجة ونقدم الإشعارات أو خيارات الموافقة اللازمة.'],
    ['هذا الموقع','تستضيف GitHub Pages الصفحات وقد تحتفظ بسجلات اتصال اعتيادية. تقيس Cloudflare Web Analytics الزيارات ومصادرها والأداء بلا ملفات تعريف ارتباط تحليلية أو تتبع عبر المواقع؛ ولا تحلل العروض أو تشغيل الصوت في التطبيق.']
  ]},
  harmonyPrivacy:{title:'سياسة خصوصية HarmonyOS',intro:'كيفية معالجة Tingbo لملفات PPTX والملاحظات على جهاز HarmonyOS.',sections:[
    ['نظرة عامة','يستورد التطبيق ملفات PPTX ويعرض الشرائح ويقرأ الملاحظات. لا يلزم حساب؛ تُعالج الملفات والشرائح والملاحظات على جهازك فقط ولا تُرفع إلى خوادمنا أو خوادم أطراف أخرى.'],
    ['جمع المعلومات','لا يجمع التطبيق أو يخزن أو يرفع الاسم أو الهاتف أو البريد أو معرّفات الجهاز أو الموقع أو جهات الاتصال أو معرّفات الإعلانات أو النشاط أو محتوى العروض؛ ولا يتضمن إعلانات أو تحليلات أو أدوات تتبع.'],
    ['الملفات المحلية','لا يقرأ التطبيق إلا PPTX الذي تختاره عبر منتقي النظام. يجري فك الضغط وتحليل الصور والملاحظات محليًا؛ وتبقى الملفات والنتائج والملاحظات المعدّلة في مساحة التطبيق.'],
    ['الصوت دون اتصال','تستخدم القراءة ميزة تحويل النص إلى كلام دون اتصال في HarmonyOS Core Speech Kit. لا يُرسل نص الملاحظات أو الصوت الناتج إلى خوادمنا أو خوادم أخرى.'],
    ['الشبكة والأطراف الأخرى','لا يطلب التطبيق إذن الوصول إلى الإنترنت ولا يقدم تحويلًا سحابيًا أو نطقًا شبكيًا أو خدمة ترفع محتواك.'],
    ['الاحتفاظ والحذف','يمكنك حذف العروض من السجل. إزالة التطبيق تحذف البيانات التي يخزنها على الجهاز.'],
    ['الأطفال','التطبيق غير موجّه خصيصًا لمن هم دون 14 عامًا، ولا نجمع معلوماتهم الشخصية عن علم.'],
    ['التغييرات','إذا تغيّرت السياسة فسنحدّث الصفحة وتاريخ المراجعة.'],
    ['الاتصال','للأسئلة: m15568817011@163.com.'],
    ['تحليلات الموقع','قد تحتفظ GitHub Pages بسجلات خادم اعتيادية. تقيس Cloudflare Web Analytics الزيارات والأداء بلا ملفات تعريف ارتباط تحليلية أو تتبع عبر المواقع. ينطبق هذا على الموقع فقط؛ ولا يمنح تطبيق HarmonyOS صلاحية الإنترنت أو يرسل ملفات أو ملاحظات أو صوتًا.']
  ]}
};

export const hi = {
  nav:{navigation:'मुख्य नेविगेशन',language:'भाषा चुनें',skip:'मुख्य सामग्री पर जाएँ',home:'होम',features:'सुविधाएँ',allFeatures:'सभी सुविधाएँ देखें',notes:'नोट्स सुनने की गाइड',rehearsal:'प्रस्तुति का अभ्यास',privacy:'गोपनीयता नीति',terms:'उपयोग की शर्तें',support:'संपर्क करें',download:'App Store से डाउनलोड करें',originalVersion:'मूल संस्करण'},
  home:{eyebrow:'Tingbo · स्लाइड नोट्स को सुनें',title:'अपनी स्क्रिप्ट सुनें, आत्मविश्वास से प्रस्तुत करें',description:'Tingbo हर स्लाइड के नोट्स पढ़ता है, अगली स्लाइड पर अपने-आप जाता है और फ़ोन पर PPT, PPTX तथा Keynote दिखाता है।',intro:'हर स्लाइड के नोट्स क्रम से सुनें। पढ़ना समाप्त होने पर अगली स्लाइड खुल सकती है; स्क्रीन लॉक होने पर भी सुनते रहें। असहज वाक्य सुधारें और दोबारा सुनें।',formats:'iPhone और iPad · PPT, PPTX, Keynote · खाते की ज़रूरत नहीं',featureEyebrow:'सुनें, सुधारें, फिर दोहराएँ',featureTitle:'स्लाइड दर स्लाइड अपनी प्रस्तुति का अभ्यास करें',featureIntro:'प्रस्तुति के वास्तविक क्रम में अपनी स्क्रिप्ट सुनें और सुधारने वाली बातें पहचानें।',readerEyebrow:'हल्का मोबाइल स्लाइड रीडर',readerTitle:'सुनते हुए स्लाइड भी देखें',readerText:'पेज बदलने के लिए स्वाइप करें, फ़ोन घुमाएँ और विवरण ज़ूम करें। नोट्स और ऑडियो नियंत्रण साथ रहते हैं।',screenshotAlt:'अंग्रेज़ी इंटरफ़ेस में स्लाइड, नोट्स और ऑडियो नियंत्रण दिखाती Tingbo स्क्रीन',screenshotCaption:'ऐप का उदाहरण (अंग्रेज़ी इंटरफ़ेस)।',stepsTitle:'तीन चरणों में अभ्यास',faqTitle:'अक्सर पूछे जाने वाले प्रश्न',ctaTitle:'मंच पर जाने से पहले स्क्रिप्ट जान लें',ctaText:'प्रस्तुति इंपोर्ट करें और सुनना शुरू करें।'},
  features:[['हर स्लाइड के नोट्स पढ़ना','डिवाइस की टेक्स्ट-टू-स्पीच सुविधा वर्तमान स्लाइड से जुड़े नोट्स पढ़ती है।'],['अपने-आप अगली स्लाइड','नोट्स पूरे होने पर अगली स्लाइड खुलती है। आप रोक, दोहरा या मैन्युअल रूप से बदल भी सकते हैं।'],['बैकग्राउंड ऑडियो','स्क्रीन लॉक होने या इयरफ़ोन लगाने पर भी सुनें; इयरफ़ोन हटते ही आवाज़ रुक जाती है।'],['अभ्यास करते हुए संपादन','नोट्स खोलें, वाक्य सुधारें, सहेजें और फिर सुनें।'],['मोबाइल स्लाइड व्यूअर','स्वाइप करें, स्क्रीन घुमाएँ और चार्ट व विवरण ज़ूम करें।'],['इतिहास और एक्सपोर्ट','पहले इंपोर्ट की गई प्रस्तुतियाँ फिर खोलें और नोट्स Markdown में या उपलब्ध होने पर PPTX कॉपी एक्सपोर्ट करें।']],
  featuresPage:{title:'Tingbo की सुविधाएँ',intro:'स्लाइड, नोट्स और आवाज़ एक ही स्क्रीन पर, ताकि अभ्यास का प्रवाह बना रहे।',formatsTitle:'फ़ाइलें और डिवाइस',formatsText:'iOS 1.2 और नए संस्करणों में .ppt, .pptx तथा .key इंपोर्ट किए जा सकते हैं। iPhone और iPad पर उपलब्ध। जटिल लेआउट फ़ाइल के अनुसार अलग दिख सकते हैं।'},
  notes:{title:'प्रस्तुति के नोट्स कैसे सुनें',intro:'हर स्लाइड के नोट्स में अपनी स्क्रिप्ट लिखें; Tingbo उन्हें क्रम से पढ़ेगा।',tip:'जिस स्लाइड में नोट्स नहीं हैं, पहले उसमें अपनी बात लिखें।',steps:[['फ़ाइल इंपोर्ट करें','Files से PPT, PPTX या Keynote (.key) चुनें और स्लाइड व नोट्स जाँचें।'],['चलाना शुरू करें','वर्तमान स्लाइड के नोट्स सुनें; समाप्त होने पर अगली स्लाइड अपने-आप खुल सकती है।'],['सुधारें और फिर सुनें','अस्वाभाविक वाक्य बदलें, सहेजें और उस स्लाइड को फिर चलाएँ।']]},
  rehearsal:{title:'प्रस्तुति सुनकर अभ्यास करें',intro:'अपनी आवाज़ में पाठ सुनने से भाषा, क्रम और बदलाव की कमियाँ पकड़ना आसान होता है।',tip:'प्रस्तुति से पहले कम-से-कम एक बार पूरी स्क्रिप्ट सुनें और सुधारे गए हिस्से फिर दोहराएँ।',steps:[['स्क्रिप्ट तैयार करें','प्रस्तुति इंपोर्ट करें और हर स्लाइड के नोट्स पूरे करें।'],['शुरू से अंत तक सुनें','देखें कि बोला गया पाठ दिखाई गई स्लाइड से मेल खाता है।'],['सुधारें और दोहराएँ','वाक्य और छूटे बिंदु तब तक सुधारें जब तक बात स्वाभाविक न लगे।']]},
  faq:[['Tingbo का मुख्य काम क्या है?','हर स्लाइड के नोट्स पढ़ना, ताकि स्लाइड देखते हुए आप प्रस्तुति का अभ्यास कर सकें।'],['कौन-सी फ़ाइलें चलती हैं?','iOS 1.2 और नए संस्करणों में PPT, PPTX और Keynote (.key)।'],['क्या बैकग्राउंड में सुन सकते हैं?','हाँ, लॉक स्क्रीन पर भी; इयरफ़ोन हटने पर प्लेबैक रुक जाता है।']],
  privacy:{title:'iOS गोपनीयता नीति',intro:'प्रस्तुतियाँ, नोट्स और इस वेबसाइट की विज़िट कैसे संभाली जाती हैं।',sections:[
    ['परिचय','Tingbo स्लाइड नोट्स पढ़ता है। प्रस्तुतियाँ और नोट्स आपके डिवाइस पर रहते हैं, सिवाय नीचे बताई गई रूपांतरण सेवा के उपयोग के। Firebase वाले iOS संस्करण सुविधाओं के उपयोग को समझने के लिए Firebase Analytics का उपयोग करते हैं; हमारे कस्टम इवेंट में फ़ाइल नाम या नोट्स का पाठ नहीं होता।'],
    ['वे डेटा जो हम नहीं लेते','खाता बनाना ज़रूरी नहीं है। सामान्य उपयोग में हम नाम, ईमेल या संपर्कों और फ़ोटो की पहुँच नहीं माँगते। कस्टम एनालिटिक्स इवेंट में प्रस्तुतियाँ, फ़ाइल नाम या नोट्स का पाठ नहीं होता। क्लाउड रूपांतरण में चुनी गई फ़ाइल भेजी जा सकती है; Firebase Analytics उपयोग इवेंट और संबंधित तकनीकी डेटा संभालता है।'],
    ['डिवाइस पर प्रोसेसिंग','इंपोर्ट की गई प्रस्तुतियाँ, स्लाइड चित्र और नोट्स ऐप के स्थानीय भंडारण में रहते हैं। पढ़ने के लिए iOS की अंतर्निहित टेक्स्ट-टू-स्पीच सुविधा उपयोग होती है।'],
    ['प्रस्तुति का रूपांतरण','PPT/PPTX को चित्रों के रूप में दिखाने के लिए कुछ संस्करण फ़ाइल बदल सकते हैं। अपने स्थानीय नेटवर्क की सेवा उपयोग की जा सकती है; दूरस्थ रूपांतरण ज़रूरी होने पर यहाँ वर्णित iOS संस्करण Cloudflare Worker से कार्य बनाता है और चुनी फ़ाइल सीधे CloudConvert को भेजता है। फ़ाइल केवल आपके अनुरोधित रूपांतरण के लिए होती है, विज्ञापन या प्रोफ़ाइल बनाने के लिए नहीं।'],
    ['तीसरे पक्ष','दूरस्थ रूपांतरण में Cloudflare अनुरोध संभालता है और CloudConvert परिणाम बनाने के लिए फ़ाइल प्राप्त करता है। हम आपका डेटा बेचते या किराए पर नहीं देते। साइट GitHub Pages पर है, जो अपनी नीति के तहत IP जैसे सामान्य कनेक्शन लॉग संभाल सकता है।'],
    ['ऐप और वेबसाइट विश्लेषण','Firebase वाले iOS संस्करण Firebase Analytics से आयात प्रारूप व स्रोत, रेंडर परिणाम व अवधि, स्लाइड संख्या, पृष्ठ बदलना और पढ़ना शुरू होने के इवेंट दर्ज करते हैं। कस्टम इवेंट में फ़ाइल नाम, प्रस्तुतियाँ या नोट्स का पाठ नहीं होता। Firebase स्वचालित ऐप इवेंट और डिवाइस या ऐप इंस्टेंस पहचानकर्ता भी एकत्र कर सकता है। अलग से Cloudflare Web Analytics बिना एनालिटिक्स कुकी या विभिन्न साइटों पर व्यक्ति की ट्रैकिंग के वेबसाइट विज़िट और प्रदर्शन मापता है; यह ऐप की सामग्री नहीं पढ़ सकता।'],
    ['रखना और मिटाना','प्रस्तुतियाँ ऐप में स्थानीय रहती हैं। इतिहास से अलग-अलग फ़ाइलें मिटा सकते हैं; ऐप अनइंस्टॉल करने से डिवाइस पर उसका रखा डेटा हट जाता है।'],
    ['बच्चे','ऐप 13 वर्ष से कम आयु के बच्चों के लिए नहीं है; हम जानबूझकर उनकी व्यक्तिगत जानकारी नहीं लेते।'],
    ['बदलाव','हम नीति अपडेट करके नई तारीख दिखा सकते हैं। लागू होने के बाद ऐप का उपयोग जारी रखने का अर्थ नई नीति स्वीकार करना है।'],
    ['संपर्क','गोपनीयता संबंधी प्रश्न: m15568817011@163.com।']
  ]},
  terms:{title:'iOS उपयोग की शर्तें',intro:'iOS पर Tingbo इस्तेमाल करने से पहले ये शर्तें पढ़ें।',sections:[
    ['स्वीकृति','Tingbo डाउनलोड, इंस्टॉल या उपयोग करने पर आप इन शर्तों को मानते हैं। असहमत हों तो ऐप उपयोग न करें।'],
    ['लाइसेंस','इन शर्तों और Apple App Store की शर्तों के अधीन, आपको अपने Apple डिवाइस पर निजी, गैर-व्यावसायिक उपयोग के लिए सीमित, गैर-अनन्य, अहस्तांतरणीय और वापस लिया जा सकने वाला लाइसेंस मिलता है।'],
    ['आपकी सामग्री','इंपोर्ट की गई प्रस्तुतियों और नोट्स पर आपके अधिकार बने रहते हैं। उन्हें उपयोग और प्रोसेस करने की अनुमति होना आपकी ज़िम्मेदारी है।'],
    ['ऐप कैसे काम करता है','ऐप स्लाइड को चित्र के रूप में दिखाता है और डिवाइस की आवाज़ से नोट्स पढ़ता है। रूपांतरण आपके स्थानीय नेटवर्क पर हो सकता है; दूरस्थ सेवा चुनने पर चुनी फ़ाइल केवल अनुरोधित रूपांतरण के लिए तीसरे पक्ष द्वारा प्रोसेस हो सकती है। गोपनीयता नीति देखें।'],
    ['मान्य उपयोग','ऐप की रिवर्स इंजीनियरिंग, डीकंपाइल या अलग-अलग हिस्से न करें; अवैध रूप से उपयोग, कॉपी, बिक्री, किराया, उप-लाइसेंस या वितरण न करें; बिना अधिकार सामग्री इंपोर्ट न करें।'],
    ['तीसरे पक्ष की सेवाएँ','दूरस्थ रूपांतरण प्रदाता स्लाइड चित्र बनाने के लिए फ़ाइलें प्रोसेस कर सकते हैं। वेबसाइट होस्टिंग और अन्य सेवाओं की अपनी शर्तें व नीतियाँ हैं।'],
    ['बौद्धिक संपदा','ऐप का डिज़ाइन, कोड, चित्र और अन्य सामग्री हमारी या लाइसेंस देने वालों की है और कानून से सुरक्षित है। कोई अतिरिक्त अधिकार नहीं दिया जाता।'],
    ['वारंटी का अस्वीकरण','ऐप “जैसा है” और “जैसा उपलब्ध है” प्रदान किया जाता है, बिना स्पष्ट या निहित वारंटी के, जिसमें बिक्री योग्यता, किसी उद्देश्य के लिए उपयुक्तता और अधिकार न उल्लंघन शामिल हैं। हम बिना रुकावट, बिना त्रुटि या पूर्ण सुरक्षा का वादा नहीं करते।'],
    ['दायित्व की सीमा','कानून की अधिकतम अनुमति तक, उपयोग से होने वाले अप्रत्यक्ष, आकस्मिक, विशेष, परिणामी या दंडात्मक नुकसान, लाभ या डेटा की हानि के लिए हम उत्तरदायी नहीं हैं, भले हमें संभावना बताई गई हो।'],
    ['समाप्ति','आप कभी भी उपयोग बंद कर सकते हैं। शर्तों के उल्लंघन पर हम लाइसेंस रोक या समाप्त कर सकते हैं; तब ऐप का उपयोग बंद करके उसे डिवाइस से हटाएँ।'],
    ['शर्तों में बदलाव','हम नई तारीख के साथ शर्तें बदल सकते हैं। लागू होने के बाद उपयोग जारी रखना स्वीकृति है।'],
    ['लागू कानून','आपके निवास के देश या क्षेत्र का कानून लागू होगा, बिना अनिवार्य उपभोक्ता अधिकारों को सीमित किए।'],
    ['संपर्क','प्रश्नों के लिए: m15568817011@163.com।']
  ]},
  androidPrivacy:{title:'Android गोपनीयता नीति',intro:'Android पर Tingbo फ़ाइलें, आवाज़ और डेटा कैसे संभालता है; 13 वर्ष या उससे अधिक उम्र के लिए।',sections:[
    ['स्थानीय फ़ाइलें और डेटा','Android फ़ाइल पिकर से इंपोर्ट के बाद ऐप कार्यशील कॉपी, स्लाइड, नाम और समय, बदले गए नोट्स, इतिहास, प्राथमिकताएँ और आवाज़ व एक्सपोर्ट कैश स्थानीय रूप से रखता है। एक्सपोर्ट आपकी चुनी जगह पर जाता है, जो क्लाउड सेवा भी हो सकती है।'],
    ['ऑनलाइन रूपांतरण','ऑनलाइन रूपांतरण या रेंडरिंग आवश्यक होने पर पूरी चुनी प्रस्तुति अपलोड होती है, जिसमें पाठ, चित्र, नोट्स और एम्बेड की गई सामग्री हो सकती है। मूल फ़ाइल Cloudflare Worker से CloudConvert तक जाती है और परिणाम Worker से लौटता है। CloudConvert के अनुसार कार्य और डेटा पूरे होने के 24 घंटे बाद अपने-आप मिटते हैं; उसकी नीति के अनुसार IP, User-Agent, समय और सेवा आँकड़ों के लॉग 180 दिन रखे जा सकते हैं। Cloudflare नेटवर्क व अनुरोध डेटा संभाल सकता है; प्रदाता विदेश में प्रोसेस कर सकते हैं।'],
    ['Android की बोलने वाली सुविधा','नोट्स डिवाइस के सक्रिय टेक्स्ट-टू-स्पीच इंजन को दिए जाते हैं। फ़ाइल खोलने, पेज बदलने या नोट्स संपादित करने पर वर्तमान और आसपास के पन्नों का पाठ प्ले दबाने से पहले तैयार हो सकता है। पूरी तरह ऑफ़लाइन काम करना इंजन, आवाज़ और सेटिंग पर निर्भर है; ऑनलाइन आवाज़ पाठ और अनुरोध डेटा प्रदाता को भेज सकती है। इंजन सिस्टम सेटिंग में बदलें।'],
    ['बैकअप और स्थानांतरण','सक्रिय होने पर Android या निर्माता, संस्करण, खाते और सेटिंग के अनुसार प्रस्तुतियों और प्राथमिकताओं सहित योग्य ऐप डेटा का बैकअप, स्थानांतरण या पुनर्स्थापन कर सकते हैं। यह Tingbo की रूपांतरण सेवा से अलग है।'],
    ['रखना और मिटाना','इतिहास से प्रस्तुति हटाने पर स्थानीय कॉपी, बदले नोट्स और रिकॉर्ड हटते हैं, पर सभी आवाज़ या एक्सपोर्ट कैश शायद न हटें। एक्सपोर्ट, अन्य सेवाओं के मूल और सिस्टम बैकअप अलग संभालें। ऐप में हटाने से रूपांतरण प्रदाता को तत्काल हटाने का अनुरोध नहीं जाता; उसके नियम लागू हैं। सहायता के लिए पहले पूरी प्रस्तुति संलग्न किए बिना लिखें।'],
    ['सहायता','सहायता या गोपनीयता अनुरोध पर हमें आपका पता, संदेश और स्वेच्छा से भेजे संलग्नक मिलते हैं और हम उत्तर के लिए उनका उपयोग करते हैं। अनावश्यक व्यक्तिगत डेटा न भेजें।'],
    ['बच्चे','ऐप 13 वर्ष या अधिक आयु के लिए है, छोटे बच्चों के लिए नहीं। यदि बच्चे ने डेटा भेजा है, हमसे संपर्क करें; माता-पिता की भागीदारी के स्थानीय नियम लागू रहते हैं।'],
    ['सुरक्षा और बदलाव','ऑनलाइन रूपांतरण HTTPS उपयोग करता है, लेकिन यह एंड-टू-एंड एन्क्रिप्शन नहीं है और प्रदाता को फ़ाइल पढ़ने से नहीं रोकता। आवाज़ इंजन और बैकअप की अपनी सेटिंग हैं। प्रोसेसिंग बदलने पर नीति अपडेट होगी और आवश्यक सूचना या सहमति दी जाएगी।'],
    ['यह वेबसाइट','GitHub Pages पेज होस्ट करता है और सामान्य लॉग रख सकता है। Cloudflare Web Analytics बिना एनालिटिक्स कुकी या वेबसाइटों के बीच ट्रैकिंग के विज़िट, स्रोत और प्रदर्शन मापता है; यह प्रस्तुतियाँ या ऐप प्लेबैक नहीं देखता।']
  ]},
  harmonyPrivacy:{title:'HarmonyOS गोपनीयता नीति',intro:'HarmonyOS पर Tingbo आपके डिवाइस में PPTX और नोट्स कैसे संभालता है।',sections:[
    ['परिचय','ऐप PPTX इंपोर्ट करता है, स्लाइड दिखाता है और नोट्स पढ़ता है। खाते की ज़रूरत नहीं; फ़ाइलें, स्लाइड और नोट्स केवल डिवाइस पर प्रोसेस होते हैं, हमारे या किसी तीसरे पक्ष के सर्वर पर अपलोड नहीं होते।'],
    ['डेटा संग्रह','ऐप नाम, फ़ोन, ईमेल, डिवाइस पहचान, स्थान, संपर्क, विज्ञापन ID, उपयोग व्यवहार या प्रस्तुति सामग्री एकत्र, स्टोर या अपलोड नहीं करता; इसमें विज्ञापन, विश्लेषण या ट्रैकिंग नहीं है।'],
    ['स्थानीय फ़ाइलें','सिर्फ सिस्टम पिकर में आपकी चुनी PPTX फ़ाइल पढ़ी जाती है। अनज़िप और चित्र व नोट्स का विश्लेषण स्थानीय रूप से होता है। फ़ाइल, परिणाम और बदले नोट्स ऐप के स्थानीय भंडारण में रहते हैं।'],
    ['ऑफ़लाइन आवाज़','पढ़ने के लिए HarmonyOS Core Speech Kit का ऑफ़लाइन टेक्स्ट-टू-स्पीच उपयोग होता है। नोट्स का पाठ और बनी ऑडियो हमारे या तीसरे पक्ष के सर्वर पर नहीं जाते।'],
    ['नेटवर्क और तीसरे पक्ष','ऐप इंटरनेट की अनुमति नहीं माँगता और नेटवर्क सेवा, क्लाउड रूपांतरण, ऑनलाइन आवाज़ या सामग्री अपलोड करने वाली सेवा नहीं देता।'],
    ['रखना और मिटाना','इतिहास से प्रस्तुतियाँ हटा सकते हैं। ऐप अनइंस्टॉल करने से डिवाइस पर उसका रखा डेटा मिट जाता है।'],
    ['बच्चे','ऐप विशेष रूप से 14 वर्ष से कम उम्र के बच्चों के लिए नहीं है और हम जानबूझकर उनका व्यक्तिगत डेटा नहीं लेते।'],
    ['बदलाव','नीति बदलने पर हम इस पेज और अद्यतन तिथि को अपडेट करेंगे।'],
    ['संपर्क','प्रश्नों के लिए: m15568817011@163.com।'],
    ['वेबसाइट विश्लेषण','GitHub Pages सामान्य सर्वर लॉग रख सकता है। Cloudflare Web Analytics बिना एनालिटिक्स कुकी या अन्य साइटों पर ट्रैकिंग के विज़िट और प्रदर्शन मापता है। यह केवल वेबसाइट पर लागू है; HarmonyOS ऐप को इंटरनेट अनुमति नहीं देता और फ़ाइल, नोट्स या ऑडियो नहीं भेजता।']
  ]}
};
